
<div class="universities">
    <div class="">
        <div class="section">
            <div class="row">
                <hr class="section-title-line">
                <h2 class="capitalize section-title"><?php echo (($lang == 'ar') ? "بعض شركاء الجامعة الروس" : (($lang == 'en') ? "SOME OF OUR RUSSIAN UNIVERSITIES PARTNERS" : "CERTAINES DE NOS UNIVERSITES RUSSES  PARTENAIRES")); ?></h2>
            </div>
            <div class="row">
                <ul class="list-group">
                    <li class="list-group-item"><a href="pages/russia/universities/russian-national-research-medical-university-named-ni-pirogov.php?lang=<?php echo $lang;?>" target="blank"><?php echo (($lang == 'ar') ? "أبحاث الجامعة الوطنية الروسية الطبية N.I.Pirogov <span class='italic'>(مدينة موسكو)</span>" : (($lang == 'en') ? "Russian National Medical University Research N.I.Pirogov <span class='italic'>(Moscow City)</span>" : "Université nationale russe médicale de la recherche N.I.Pirogov <span class='italic'>(ville de Moscou)</span>")); ?></a></li>
                    <li class="list-group-item"><a href="pages/russia/universities/chechen-state-university.php?lang=<?php echo $lang;?>" target="blank"><?php echo (($lang == 'ar') ? "جامعة ولاية الشيشان ، <span class='italic'>(مدينة غروزني)</span>" : (($lang == 'en') ? "Chechen State University <span class='italic'>(Grozny city)</span>" : "Université d'État Tchétchéne <span class='italic'>(ville Grozny)</span>")); ?></a></li>
                    <li class="list-group-item"><a href="pages/russia/universities/dagestan-state-medical-university.php?lang=<?php echo $lang;?>" target="blank"><?php echo (($lang == 'ar') ? "جامعة داغستان الطبية الحكومية ، <span class='italic'>(مدينة ماخاتشكالا)</span>" : (($lang == 'en') ? "Dagestan State Medical University <span class='italic'>(Makhachkala City)</span>" : "Université d'État de Médecine du Daghestan <span class='italic'>(ville Makhatchkala)</span>")); ?></a></li>
                    <li class="list-group-item"><a href="pages/russia/universities/moscow-institute-physics-technology.php?lang=<?php echo $lang;?>" target="blank"><?php echo (($lang == 'ar') ? "معهد موسكو للفيزياء والتكنولوجيا ، <span class='italic'>(مدينة موسكو)</span>" : (($lang == 'en') ? "Moscow Institute of Physics and Technology <span class='italic'>(Moscow City)</span>" : "Institut de Physique et de Technologie de Moscou <span class='italic'>(ville Moscou)</span>")); ?></a></li>
                    <li class="list-group-item"><a href="pages/russia/universities/kalashnikov-izhevsk-state-technical-university.php?lang=<?php echo $lang;?>" target="blank"><?php echo (($lang == 'ar') ? "جامعة إزيفسك الحكومية التقنية ، <span class='italic'>(مدينة إزيفسك)</span>" : (($lang == 'en') ? "Izhevsk Technical State University of Mr. T. Kalashnikov <span class='italic'>(Izhevsk city)</span>" : "Université  d’Etat Technique d’Izhevsk M.T. Kalachnikov <span class='italic'>(ville Izhevsk)</span>")); ?></a></li>
                    <li class="list-group-item"><a href="pages/russia/universities/Polytechnic-University-Tomsk.php?lang=<?php echo $lang;?>" target="blank"><?php echo (($lang == 'ar') ? "جامعة البوليتكنيك في تومسك ، <span class='italic'>(مدينة تومسك)</span>" : (($lang == 'en') ? "Polytechnic University of Tomsk <span class='italic'>(Tomsk City)</span>" : "Université Polytechnique de Tomsk <span class='italic'>(ville Tomsk)</span>")); ?></a></li>
                    <li class="list-group-item"><a href="pages/russia/universities/rybinsk-state-aviation-technical-university.php?lang=<?php echo $lang;?>" target="blank"><?php echo (($lang == 'ar') ? "جامعة ولاية هندسة الطيران بمدينة Rybinsk <span class='italic'>(مدينة Rybinsk)</span>" : (($lang == 'en') ? "State Technical University of Rybinsk Aviation <span class='italic'>(Rybinsk City)</span>" : "Université d'État Technique de l'Aviation de Rybinsk <span class='italic'>(ville Rybinsk)</span>")); ?></a></li>
                    <li class="list-group-item"><a href="pages/russia/universities/ogarev-state-university.php?lang=<?php echo $lang;?>" target="blank"><?php echo (($lang == 'ar') ? "جامعة Mordovia State NPOgaraev ، <span class='italic'>مدينة سارانسك</span>" : (($lang == 'en') ? "Mordovia State University NPOgaraev <span class='italic'>Saransk city</span>" : "Université d’Etat de Mordovie N.P.Ogaraev  <span class='italic'>ville Saransk</span>")); ?></a></li>
                    <li class="list-group-item"><a href="pages/russia/universities/adyghe-state-university.php?lang=<?php echo $lang;?>" target="blank"><?php echo (($lang == 'ar') ? "جامعة أديغيا الحكومية ، <span class='italic'>(مدينة مايكوب)</span>" : (($lang == 'en') ? "Adygea State University <span class='italic'>(Maïkop City)</span>" : "Université d’Etat Adyguée <span class='italic'>(ville Maïkop)</span>")); ?></a></li>
                    <li class="list-group-item"><a href="pages/russia/universities/first-moscow-state-medical-university-named-m-sechenova.php?lang=<?php echo $lang;?>" target="blank"><?php echo (($lang == 'ar') ? "أول جامعة موسكو الحكومية الطبية ، <span class='italic'>(مدينة موسكو)</span>" : (($lang == 'en') ? "The First Moscow State Medical University <span class='italic'>(Moscow City)</span>" : "La Première Université médicale d’Etat de Moscou <span class='italic'>(ville Moscou)</span>")); ?></a></li>
                    <!-- <li class="list-group-item"><a href="pages/russia/universities/siberian-state-medical-university.php?lang=<?php echo $lang;?>" target="blank"><?php echo (($lang == 'ar') ? "جامعة سيبيريا ستيت الطبية ، <span class='italic'>مدينة تومسك</span>" : (($lang == 'en') ? "Siberian State Medical University <span class='italic'>Tomsk City</span>" : "Université Médicale d'État DE Sibérie <span class='italic'>ville Tomsk</span>")); ?></a></li> -->
                    <!-- <li class="list-group-item"><a href="pages/russia/universities/admiral-state-university-maritime.php?lang=<?php echo $lang;?>" target="blank"><?php echo (($lang == 'ar') ? "جامعة ولاية البحرية الأدميرال أوشاكوف ، <span class='italic'>مدينة نوفوروسيي</span>" : (($lang == 'en') ? "Maritime State University of Admiral Ushakov <span class='italic'>Novorossiysh City</span>" : "Université d’Etat Maritime de l’Admiral Ushakov <span class='italic'>Ville Novorossiisk</span>")); ?></a></li> -->
                    <!-- <li class="list-group-item"><a href="pages/russia/universities/belgorod-institute-art-culture.php?lang=<?php echo $lang;?>" target="blank"><?php echo (($lang == 'ar') ? "" : (($lang == 'en') ? "" : "")); ?></a></li> -->
                </ul>
            </div>
        </div>
    </div>
</div>
