<?php $path = $_SERVER['DOCUMENT_ROOT'];
    include $path.'/layouts/header.php'  ;
    $title = get_lang_text("معلومات إضافية", "ADDITIONAL INFORMATION","INFORMATIONS  SUPPLÉMENTAIRES");
    title_page($title)
?>
    
<?php include $path.'/layouts/feature.php';
    $txt = "Cours";
    if(isset($_GET['lang'])){
        $txt = translate_feature_txt("INFORMATIONS  SUPPLÉMENTAIRES", "معلومات إضافية", "ADDITIONAL INFORMATION");
    }
    feature_txt($txt, "courses");
?>

<div class="section additional-infos">
    <div class="row">
        <hr class="section-title-line">
        <h2 class="section-title"><?php echo (($lang == 'ar') ? "معلومات إضافية :" : (($lang == 'en') ? "ADDITIONAL INFORMATION :" : "INFORMATIONS  SUPPLEMENTAIRES :")); ?></h2>
        <h3><?php echo (($lang == 'ar') ? "معادلات" : (($lang == 'en') ? "Equivalences:" : "Équivalences :")); ?></h3>
        <p><?php echo (($lang == 'ar') ? "توجد قائمة بالجامعات المعتمدة من قبل وزارة التعليم العالي الأوكرانية والمعترف بها في المغرب لطلب التكافؤ على موقع وزارة التعليم العالي والبحث العلمي والتدريب للمدراء: <a href='https://enssup.gov.ma/sites/default/files/PAGES/2025/liste_etab_ukraine_07_03_2016.pdf' target='_blank' class='underline'>الرابط</a>" : (($lang == 'en') ? "The list of universities accredited by the Ministry of Higher Education of Ukraine and recognized in Morocco for a request for equivalence is on the website of the Ministry of Higher Education, Scientific Research and Training of Managers: <a href='https://enssup.gov.ma/sites/default/files/PAGES/2025/liste_etab_ukraine_07_03_2016.pdf' target='_blank' class='underline'>link</a>" : "La liste des universités accréditées par le Ministère de l’Enseignement Supérieur Ukrainien et reconnues au Maroc pour une demande d’équivalence est sur le site du Ministère de l’Enseignement Supérieur, de la Recherche Scientifique et de la Formation des Cadres : <a target='_blank' href='https://enssup.gov.ma/sites/default/files/PAGES/2025/liste_etab_ukraine_07_03_2016.pdf' class='underline'>lien</a>")); ?></p>
        <p><?php echo (($lang == 'ar') ? "قائمة الجامعات التي أوصى بها الاتحاد الروسي: <a target='_blank' class='underline' href='https://www.enssup.gov.ma/sites/default/files/PAGES/2025/RUSSIE_accreditation_UNIVERSITES-RUSSIE_avril_2018.pdf'>الرابط</a>" : (($lang == 'en') ? "List of universities recommended by the Russian Federation: <a target='_blank' class='underline' href='https://www.enssup.gov.ma/sites/default/files/PAGES/2025/RUSSIE_accreditation_UNIVERSITES-RUSSIE_avril_2018.pdf'>link</a>" : "Liste des universités recommandées par la fédération de Russie : <a target='_blank' class='underline' href='https://www.enssup.gov.ma/sites/default/files/PAGES/2025/RUSSIE_accreditation_UNIVERSITES-RUSSIE_avril_2018.pdf'>lien</a>")); ?></p>
        <p><?php echo (($lang == 'ar') ? "مراحل عملية تكافؤ الدبلوم: <a target='_blank' class='underline' href='https://www.enssup.gov.ma/sites/default/files/PAGES/2025/Processus_EquivalenceDiplome.pdf'>الرابط</a>" : (($lang == 'en') ? "The phases of the diploma equivalence process: <a target='_blank' class='underline' href='https://www.enssup.gov.ma/sites/default/files/PAGES/2025/Processus_EquivalenceDiplome.pdf'>link</a>" : "Les phases du processus d’équivalence de diplômes : <a target='_blank' class='underline' href='https://www.enssup.gov.ma/sites/default/files/PAGES/2025/Processus_EquivalenceDiplome.pdf'>lien</a>")); ?></p>
        <p><?php echo (($lang == 'ar') ? "الموقع <a target='_blank' class='underline' href='https://www.enssup.gov.ma/'>enssup.gov.ma</a> هو موقع وزارة التعليم العالي والبحث العلمي وتدريب المديرين." : (($lang == 'en') ? "The site <a target='_blank' class='underline' href='https://www.enssup.gov.ma/'>enssup.gov.ma</a> is that of the Ministry of Higher Education, Scientific Research and Training of Managers." : "Le site <a target='_blank' class='underline' href='https://www.enssup.gov.ma/'>enssup.gov.ma</a> est celui du Ministère de l’Enseignement Supérieur, de la Recherche Scientifique et de la Formation des Cadres.")); ?></p>
    </div>
    <div class="row">
        <hr class="section-title-line">
        <h2 class="section-title"><?php echo (($lang == 'ar') ? "لتعرف" : (($lang == 'en') ? "To know :" : "A Savoir :")); ?></h2>
    </div>
    <div class="row">
        <hr class="section-title-line">
        <h2 class="section-title"><?php echo (($lang == 'ar') ? "هل يجب علي تقديم شهادة تؤكد معرفتي باللغة الإنجليزية / الفرنسية؟" : (($lang == 'en') ? "Do I have to present a certificate confirming my knowledge of English / French?" : "Est-ce qu’il faut présenter un certificat confirmant mes connaissances de l’anglais / du français?")); ?></h2>
        <p><?php echo (($lang == 'ar') ? "ليست هناك حاجة لتقديم نتائج الاختبارات الدولية مثل IELTS ، TOEFL ، CAE ، DALF ، TCF إلخ. حتى إذا سجل الطلاب للتدريب في اللغة الإنجليزية أو الفرنسية ، يجب أن يكون لديهم مقابلة عند الوصول حتى تتمكن الجامعة من فحص وتأكيد مستوى اللغة. للتسجيل في الدراسات ، يكفي تقديم وثيقة تثبت أن المرشح قام بتدقيق دورات اللغة الإنجليزية / الفرنسية (على سبيل المثال ، نسخة من BAC أو الترخيص)." : (($lang == 'en') ? "There is no need to present the results of international tests like IELTS, TOEFL, CAE, DALF, TCF etc. Even if students register for training in English or French, they must have an interview upon arrival so that the University can examine and confirm the level of the language. For the registration to the studies it suffices to present a document attesting that the candidate has validated courses of the English / French language (for example, the transcript of the BAC or License)." : "Il n’y a pas besoin de présenter les résultats des tests internationaux comme IELTS, TOEFL, CAE, DALF, TCF etc. Quand même les étudiants qui s’inscrivent à la formation en anglais ou en français, doivent passer un entretien à leur arrivée pour que l’Université puisse examiner et confirmer le niveau de la langue. Pour l’inscription aux études il suffit de présenter un document attestant que le candidat a validé des cours de la langue anglaise / française (par exemple, le relevé de notes du BAC ou de Licence).")); ?></p>
    </div>
    <div class="row">
        <hr class="section-title-line">
        <h2 class="section-title"><?php echo (($lang == 'ar') ? "ادرس في جامعة في بلدي. نقل إلى الجامعة الروسية ، هل من الممكن؟" : (($lang == 'en') ? "I study at a university in my country. Transfer to Russian university, is it possible?" : "Je fais mes études dans une université dans mon pays. Le transfert à l’université russe, est-il possible?")); ?></h2>
        <p><?php echo (($lang == 'ar') ? "يُحظر النقل من الجامعة الأجنبية إلى الجامعة الروسية وفقًا لقانون روسيا. يمكن التسجيل في السنة الأولى فقط من الجامعة الروسية. ومع ذلك ، فإن الطلاب لديهم الحق في تقديم نصوص تصادق على عدد معين من الدورات التي تم التحقق منها في الجامعة الأجنبية. في هذه الحالة ، تقوم اللجنة الخاصة بفحص الوثائق من خلال مقارنة محتويات البرنامجين ، لتحديد الفرق بين برامج جامعتين ، ومع ذلك يمكنها اتخاذ القرار بالسماح بنقل مثل هذا الطالب أو هذا الطالب لمثل هذه البرامج أو هذا العام وفقا لوثائق التعليم السابقة المقدمة. من الممكن أيضًا اجتياز الاختبارات في موضوعات معينة. قد يختلف الحل من حالة إلى أخرى ، لمرشح معين." : (($lang == 'en') ? "Transfers from the foreign university to the Russian university are prohibited according to the law of Russia. It is only possible to enroll in the first year of the Russian university. Even so, students have the right to present transcripts attesting a certain number of courses validated at the foreign university. In this case the special commission examines the documents by comparing the contents of two programs, to identify the difference between the programs of two universities, and yet it could make the decision to allow the transfer of such or such student for such or this year in accordance with the previous education documents presented. It is also possible to pass exams in certain subjects. The solution may vary from one situation to another, for a particular candidate." : "Les transferts de l’université étrangère à l’université russe sont interdits selon la loi de la Russie. Il est seulement possible de s’inscrire en 1ère année de l’université russe. Quand même les étudiants ont droit de présenter les relevés de notes attestant un certain nombre des cours validés à l’université étrangère. En ce cas la commission spéciale examine les documents en comparant le contenu de deux programmes, pour identifier la difference entre les programmes de deux universités, et cependant elle pourrait prendre la décision de permettre le transfert d‘un tel ou tel étudiant pour une telle ou telle année en conformité avec les documents d’éducation anterieure présentés. Il est également possible de passer les examens en certaines matières. La solution peut varier d’une situation à l’autre, pour un tel ou tel candidat.")); ?></p>
        <p><?php echo (($lang == 'ar') ? "يمكنك الوصول إلى المستوى التالي من التعليم بعد التخرج من جامعتك. على سبيل المثال ، إذا كان لديك شهادة ، يمكنك التسجيل للحصول على درجة الماجستير في روسيا." : (($lang == 'en') ? "You can access the next level of education after graduating from your university. For example if you have a degree, you can register for a Master in Russia." : "Vous pouvez accéder au niveau des études suivant après avoir obtenu le diplôme dans votre université. Par exemple si vous avez le diplôme de Licence, vous pouvez vous inscrire en Master en Russie.")); ?></p>
    </div>
    <div class="row">
        <hr class="section-title-line">
        <h2 class="section-title"><?php echo (($lang == 'ar') ? "ما هي الوثائق التي أحتاج إلى إعدادها قبل القدوم إلى روسيا؟" : (($lang == 'en') ? "What documents do I need to prepare before coming to Russia?" : "Quels documents est-ce que je dois préparer avant de venir en Russie?")); ?></h2>
        <p><?php echo (($lang == 'ar') ? "عندما يصل الطالب إلى روسيا ، عليه أن يودع في الجامعة القائمة التالية بالوثائق الإلزامية:" : (($lang == 'en') ? "When the student arrives in Russia, he must deposit at the university the following list of the obligatory documents:" : "Quand l’étudiant arrive en Russie, il doit déposer à l’université la liste suivante des documents obligatoires:")); ?></p>
        <ul class="list-group">
            <il class="list-group-item"><?php echo (($lang == 'ar') ? "أصل شهادة BAC مع شهادة الدرجات الأصلية / شهادة البكالوريوس أو الماجستير مع النسخة القانونية من وزارة الخارجية في بلدك (أو من خلال هيئة أخرى منشأة بموجب تشريع بلد الإقامة ) وسفارة الاتحاد الروسي في البلد الذي أصدر مستنداتك التعليمية (أو مع أبوستيل لدى الدول الموقعة على اتفاقية لاهاي)" : (($lang == 'en') ? "The BAC diploma originals with the transcript / original diploma of the Bachelor or Master with the legalized transcript from the Ministry of Foreign Affairs of your country (or via another body established by the legislation of your country of residence ) and by the Embassy of the Russian Federation in the country that issued your educational documents (or with the Apostille for the signatory countries of the Hague Convention)" : "Les originaux de diplôme du BAC avec le Relevé de notes/ les originaux de diplôme de Licence ou Master avec le Relevé de notes légalisés auprès du Ministère des Affaires Etrangères de votre pays (ou via un autre organisme établi par la législation de votre pays de résidence) et par l’Ambassade de la Fédération de Russie dans le pays qui a délivré vos documents éducatifs (ou bien avec l’Apostille pour les pays signataires de la Convention de La Haye)")); ?></il>
            <il class="list-group-item"><?php echo (($lang == 'ar') ? "شهادة التطعيم أو شهادة طبية مع معلومات عن جميع اللقاحات التي تم إجراؤها ؛" : (($lang == 'en') ? "Certificate of vaccination or a medical certificate with information on all vaccinations made;" : "Certificat de vaccination ou bien un certificat médical avec l’information sur toutes les vaccinations faites;")); ?></il>
            <il class="list-group-item"><?php echo (($lang == 'ar') ? "شهادة غياب الإيدز / فيروس نقص المناعة البشرية (تصوير) ؛" : (($lang == 'en') ? "Certificate of absence of AIDS / HIV (photocopy);" : "Certificat d’absence de SIDA / VIH (photocopie);")); ?></il>
            <il class="list-group-item"><?php echo (($lang == 'ar') ? "12 صورة 3x4 سم ، بالألوان ، ورق غير لامع." : (($lang == 'en') ? "12 pictures 3x4 cm, in color, matte paper." : "12 photos 3x4 cm, en couleur, papier mat.")); ?></il>
        </ul>
    </div>
    <div class="row">
        <hr class="section-title-line">
        <h2 class="section-title"><?php echo (($lang == 'ar') ? "ما هو تقنين الوثائق التعليمية؟" : (($lang == 'en') ? "What is the legalization of educational documents?" : "Qu’est-ce que c’est que la légalisation des documents éducatifs?")); ?></h2>
        <p><?php echo (($lang == 'ar') ? "قبل وصوله إلى روسيا ، يجب على الطالب القيام بإضفاء الشرعية على مستنداته التعليمية (مع نسخة من الملاحظات) في البلد الذي أصدر وثائقه." : (($lang == 'en') ? "Before arriving in Russia the student must do the legalization of his educational documents (with the transcript of notes) in the country that issued his documents." : "Avant d’arriver en Russie l’étudiant doit faire la légalisation de ses documents éducatifs (avec le relevé des notes) dans le pays qui a délivré ses documents.")); ?></p>
        <p><?php echo (($lang == 'ar') ? "هناك نوعان من التقنين: التشريع القنصلي و Apostille (الأخير مخصص للبلدان الموقعة على اتفاقية لاهاي)." : (($lang == 'en') ? "There are two types of legalization: consular legalization and the Apostille (the latter is intended for countries signatory to the Hague Convention)." : "Il existe deux types de légalisation: la légalisation consulaire et l’Apostille (ce dernier est prévu pour les pays signataires de la Convention de La Haye).")); ?></p>
        <p><?php echo (($lang == 'ar') ? "التشريع القنصلي يشمل:" : (($lang == 'en') ? "Consular legalization includes:" : "La légalisation consulaire comprend:")); ?></p>
        <ul class="list-group">
            <li class="list-group-item"><?php echo (($lang == 'ar') ? "ختم التصديق من وزارة خارجية البلد الذي أصدر الوثائق (أو من قبل هيئة أخرى مسؤولة)." : (($lang == 'en') ? "The stamp of legalization by the Ministry of Foreign Affairs of the country that issued the documents (or by another responsible body)." : "Le cachet de légalisation par le Ministère des Affaires Etrangères du pays qui a délivré les documents (ou bien par un autre organisme responsable).")); ?></li>
            <li class="list-group-item"><?php echo (($lang == 'ar') ? "ختم التصديق من قبل السفارة (القنصلية العامة) للاتحاد الروسي في البلد الذي أصدر الوثائق." : (($lang == 'en') ? "The stamp of legalization by the Embassy (Consulate General) of the Russian Federation in the country that issued the documents." : "Le cachet de légalisation par l’Ambassade (le Consulat Général) de la Fédération de Russie dans le pays qui a délivré les documents.")); ?></li>
        </ul>
        <p><?php echo (($lang == 'ar') ? "إذا كانت الدولة التي أصدرت الوثائق التعليمية هي إحدى الدول الموقعة على اتفاقية لاهاي ، فلا يلزم سوى ختم واحد ، بما في ذلك الأبوستيل (في معظم الحالات يتم إجراء الأبوستيل من قبل وزارة الشؤون الخارجية)." : (($lang == 'en') ? "If the country that issued the educational documents is a signatory to the Hague Convention, only one stamp is required, including the Apostille (in most cases the Apostille is made by the Ministry of Foreign Affairs)." : "Si le pays qui a délivré les documents éducatifs est un pays signataire de la Convention de la Haye, il suffit seulement un seul cachet, notamment l’Apostille (dans la plupart des cas l’Apostille est fait par le Ministère des Affaires Etrangères).")); ?></p>
        <p><?php echo (($lang == 'ar') ? "تتم المصادقة إما على أصول شهادة الدبلوم (من BAC ، أو الترخيص أو الماجستير) مع نسخة من الملاحظات ، أو على نسخ موثقة من هذه الوثائق." : (($lang == 'en') ? "The legalization is done either on the originals of diploma (of the BAC, License or Master) with the Transcript of notes, or on the notarized copies of these documents." : "La légalisation se fait soit sur les originaux de diplôme (du BAC, de Licence ou de Master) avec le Relevé de notes, soit sur les copies notariées de ces documents.")); ?></p>
    </div>
    <div class="row">
        <hr class="section-title-line">
        <h2 class="section-title"><?php echo (($lang == 'ar') ? "ماذا يمكن أن آخذ معي؟" : (($lang == 'en') ? "What can I take with me?" : "Qu’est ce que je peux prendre avec moi?")); ?></h2>
        
        <ul class="list-group">
            <li class="list-group-item"><?php echo (($lang == 'ar') ? "حقائب اليد (عادة 8 كجم)" : (($lang == 'en') ? "Hand luggage (normally 8 kg):" : "Bagage à main (normalement 8 kg):")); ?></li>
            <li class="list-group-item"><?php echo (($lang == 'ar') ? "جواز سفر" : (($lang == 'en') ? "Passport" : "Passeport")); ?></li>
            <li class="list-group-item"><?php echo (($lang == 'ar') ? "المغلف مع جميع الوثائق" : (($lang == 'en') ? "Envelope with all documents" : "Enveloppe avec tous les documents")); ?></li>
            <li class="list-group-item"><?php echo (($lang == 'ar') ? "كمبيوتر محمول / هاتف / لوحي" : (($lang == 'en') ? "Laptop / phone / tablet" : "Ordinateur portable/téléphone/tablette")); ?></li>
            <li class="list-group-item"><?php echo (($lang == 'ar') ? "نقداً ، حوالي 500 دولار أمريكي أو يورو" : (($lang == 'en') ? "Cash, about 500 USD or Euro" : "Argent, environ 500 USD ou Euro")); ?></li>
        </ul>
        <p><?php echo (($lang == 'ar') ? "بالنسبة للأمتعة ، عادة ما تكون الرحلات المحلية والدولية 23 كيلو. من الأفضل أن تخبر الشركة عن كمية الأمتعة التي يمكنك الحصول عليها" : (($lang == 'en') ? "For luggage, normally it is 23 kilo domestic and international flights. It is better to tell the airline how much luggage you can take." : "Pour bagage, normalement c’est 23 kilo les vols intérieurs et internationaux. Il vaut mieux préciser auprès de la compagnie aérienne combien de bagage maximum vous pouvez prendre.")); ?></p>
    </div>
    <div class="row">
        <hr class="section-title-line">
        <h2 class="section-title"><?php echo (($lang == 'ar') ? "من سيرحب بي في المطار ويرافقني إلى الجامعة؟" : (($lang == 'en') ? "Who will welcome me at the airport and accompany me to the university?" : "Qui va m’accueillir à l’aéroport et m’accompagner à l’université?")); ?></h2>
        <p><?php echo (($lang == 'ar') ? "عند الوصول إلى المطار ، يجب أن تمر عبر نقطة مراقبة جوازات السفر ، وأن تستلم أمتعتك وتذهب من خلال الرقابة الجمركية. بعد الفحص الجمركي سوف تخرج في صالة الوصول في المطار حيث سيتم استقبالك من قبل ممثل RAE." : (($lang == 'en') ? "Upon arrival at the airport you will have to pass through the passport control point, receive your luggage and go through the customs control. After the customs check you will exit in the arrival hall of the airport where you will be greeted by the representative of RAE." : "A l’arrivée à l’aéroport vous devrez passer par le point de contrôle de passeports, recevoir vos bagages et passer par le contrôle douanier. Après le contrôle douanier vous sortirez dans la salle d’arrivée de l’aéroport où vous serez accueilli par le représentant de RAE .")); ?></p>
        <p><?php echo (($lang == 'ar') ? "لضمان الاستقبال والمرافقة تجاه المدينة وجامعة وجهتك ، سنقوم مسبقا بتوكيل خاص لمراقبة الجوازات والرقابة الجمركية على المطارات. وفقا للوائح الحالية ، يمكن لخدمات مراقبة الحدود منع دخول الطالب إلى روسيا إذا لم يكن هناك مسؤول بتوكيل رسمي من الجامعة المضيفة. لا تصل بمفردك دون إبلاغ RAE لتجنب المشاكل في المطار. إذا لم يكن هناك شخص لديه توكيل للترحيب بك في المطار ، فيمكن إعادة الطالب الأجنبي إلى وطنه عن طريق أقرب رحلة طيران (يجب أن يدفع الطالب جميع النفقات). لذلك يجب أن يكون لدى كل طالب تذكرة ذهاب وعودة أو نقود لشراء واحدة." : (($lang == 'en') ? "To guarantee the reception and the accompaniment towards the city and the university of your destination we will make in advance a special power of attorney for the control of passports and the customs control to the airports. According to the current regulations, the border control services can prevent the entry of a student into Russia if there is no official with a power of attorney from the host university. Do not arrive alone without informing RAE to avoid problems at the airport. If there is no one with a power of attorney to welcome you to the airport, a foreign student can be returned to his home country by the closest flight (all expenses are to be paid by the student). So each student must have a return ticket or money to buy one." : "Pour vous garantir l’accueil et l’accompagnement vers la ville et l’université de votre destination nous allons faire à l'avance une procuration spéciale pour le contrôle de passeports et le contrôle douanier aux aéroports. D’après le règlement en vigueur les services de contrôle des frontières peuvent empêcher l'entrée d’un étudiant en Russie s’il n’y a pas de responsable avec une procuration de l’Université qui l’accueille. N’arrivez pas seul sans informer RAE  afin d’éviter des problèmes à l’aéroport. S’il n’y a personne avec une procuration pour vous accueillir à l’aéroport, un étudiant étranger peut être renvoyé dans son pays natal par le vol le plus proche (toutes les dépenses sont à payer par l'étudiant). Ainsi chaque étudiant doit avoir un billet de retour ou bien de l’argent pour en acheter un.")); ?></p>
        <p><?php echo (($lang == 'ar') ? "يرجى إبلاغنا إذا كانت رحلتك متأخرة ، إذا فاتتك الطائرة ، إذا فقدت في المطار أو إذا كنت تواجه صعوبات." : (($lang == 'en') ? "Please inform us if your flight is late, if you have missed your plane, if you are lost in the airport or if you have difficulties." : "Veuillez nous informer si votre vol est en retard, si vous avez raté votre avion, si vous êtes perdu dans l’aéroport ou bien si vous avez des difficultés.")); ?></p>
        <p><?php echo (($lang == 'ar') ? "عند الوصول إلى المطار ، ستقوم شركة RAE بالاعتناء بنقلك إلى المدينة وجامعة وجهتك (بما في ذلك الاستقبال في مطار مدينة الوجهة والانتقال إلى منزل الطلاب) ، وإقامتك في المنزل ، وجميع الإجراءات اللازمة للتسجيل للدراسات في الجامعة." : (($lang == 'en') ? "Upon arrival at the airport RAE will take care of your transfer to the city and the university of your destination (including the reception at the airport of the city of your destination and the transfer to the home of students), your stay at home, all the formalities for registering for studies at the university." : "Dès l’accueil à l’aéroport RAE s’occupera de votre transfert vers la ville et l’université de votre destination (y inclus l’accueil à l’aéroport de la ville de votre destination et le transfert jusqu’au foyer d’étudiants), de votre hébergement au foyer, de toutes les formalités d’inscription aux études à l’université.")); ?></p>
    </div>
    <div class="row">
        <hr class="section-title-line">
        <h2 class="section-title"><?php echo (($lang == 'ar') ? "كيف يمكنني الاتصال بوالدي عند وصولي إلى روسيا؟" : (($lang == 'en') ? "How can I contact my parents when I arrive in Russia?" : "Comment est-ce que je peux contacter mes parents à mon arrivée en Russie?")); ?></h2>
        <p><?php echo (($lang == 'ar') ? "عند وصولك إلى روسيا ، سيقوم أحد ممثلي RAE بمساعدتك في جميع المواد ، وبالطبع سيساعدك على شراء بطاقة SIM الروسية لهاتفك المحمول لضمان تواصلك مع والديك. علاوة على ذلك ، بعد وصولك إلى روسيا ، ستقوم منظمة RAE بإبلاغ ممثل RAE في بلدك لإبلاغ والديك بأنك ستصل ، وأنك تقيم في المنزل وأن كل شيء على ما يرام." : (($lang == 'en') ? "When you arrive in Russia, one of the RAE representatives will assist you on all subjects, and of course it will help you to buy a Russian SIM card for your mobile to ensure your communication with your parents. Moreover, after your arrival in Russia, RAE organization will inform a RAE representative in your country to inform your parents that you are arriving, that you are staying at home and that everything is fine." : "A votre arrivée en Russie un des représentants de RAE vous assistera sur tous les sujets, et bien sûr qu’il vous aidera à acheter une carte SIM russe pour votre portable afin d’assurer votre communication avec vos parents. De plus après votre arrivée en Russie, organisation RAE informera un représentant de RAE dans votre pays afin qu’il informe vos parents que vous êtes arriver, que vous êtes logé au foyer et que tout est bien.")); ?></p>
    </div>
    <div class="row">
        <hr class="section-title-line">
        <h2 class="section-title"><?php echo (($lang == 'ar') ? "كم أمتعة يمكن أن آخذها؟" : (($lang == 'en') ? "How much luggage can I take?" : "Combien de bagages est-ce que je peux prendre?")); ?></h2>
        <p><?php echo (($lang == 'ar') ? "من المحبط بشدة أن يكون لديك أكثر من 20-30 كيلوغرام من الأمتعة. الأمتعة الثقيلة للغاية تنطوي على الدعوة إلى خدمة الحمالة ، والتي تكلف اضافية. يصل معظم الطلاب إلى مطار موسكو الدولي ومن هناك يأخذون القطار أو الطائرة إلى مدينة الوجهة النهائية. بالنسبة للأمتعة غير القياسية ، سيتوجب عليك دفع مبلغ إضافي (حوالي 4 يورو لكل كيلو إضافي). يمكنك العثور على جميع أنواع الأعمال والمواد الغذائية في روسيا ويمكن لموظفي RAE في المدن مساعدتك في القيام بذلك. حتى بعد دفع ثمن الأمتعة خارج الصندوق في مطار المغادرة ، سيكون عليك المرور عبر مراقبة الجمارك في روسيا. مع الأمتعة التي يبلغ وزنها 50 كجم ، سيتوجب عليك دفع الضرائب الجمركية ، وهي 4 يورو لكل كيلو من الوزن القياسي (وفقًا للتشريعات الجمركية في روسيا). يحظر جلب المنتجات الغذائية إلى روسيا. يستغرق الأمر الكثير من الوقت (ما يصل إلى 3 ساعات) لدفع ثمن الأمتعة غير القياسية ، مما قد يتسبب في تأخير الرحلة أو القطار التالي أثناء النقل." : (($lang == 'en') ? "It is strongly discouraged to have more than 20-30 kilos of luggage. Too heavy baggage involves the call to porter service, which costs extra. Most students arrive at Moscow International Airport and from there they take the train or plane to the final destination city. For non-standard luggage, you will have to pay extra (that's about 4 euros for each extra kilo). You can find all types of business and food in Russia and RAE employees in cities can help you do that. Even after paying for out-of-the-box luggage at the departure airport, you will have to go through customs control in Russia. With luggage of 50 kg you will have to pay the customs taxes, it is 4 euros for 1 kilo out of standard (according to the customs legislation in Russia). It is forbidden to bring food products to Russia. It takes a lot of time (up to 3 hours) to pay for off-standard luggage, which can cause delay for the next flight or train during the transfer." : "Il est fortement déconseillé d’avoir plus de 20-30 kilos de bagage. Les bagages trop lourds impliquent l’appel au service de porteurs, ce qui coûte des frais supplémentaires. La plupart des étudiants arrivent à l’aéroport international de Moscou et de là-bas prennent le train ou l’avion pour aller dans la ville de destination finale. Pour bagage hors normes il faudra payer un supplément (c’est à peu près 4 euros pour chaque kilo supplémentaire). Vous pouvez trouver tous les types d’affaires et de nourriture en Russie et les employés de RAE dans les villes peuvent vous aider à le faire. Même après avoir payé pour bagage hors normes à l’aéroport du départ, vous devrez passer par le contrôle douanier en Russie. Avec bagage de 50 kg il vous faudra payer les taxes de douane, c’est 4 euros pour 1 kilo hors normes (selon la législation douanière en Russie). Il est interdit d’apporter les produits alimentaires en Russie. Ça prend énormément de temps (jusqu’à 3 heures) pour payer pour bagage hors normes, ce qui peut entraîner le retard pour le vol suivant ou le train pendant le transfert.")); ?></p>
    </div>
    <div class="row">
        <hr class="section-title-line">
        <h2 class="section-title"><?php echo (($lang == 'ar') ? "كم من المال أحتاج؟" : (($lang == 'en') ? "How much money do I need?" : "Combien d’argent il me faut?")); ?></h2>
        <p><?php echo (($lang == 'ar') ? "عند الوصول إلى مطار موسكو / سانت بطرسبرغ ، يجب أن يكون لدى الطلاب (بالإضافة إلى بطاقة الائتمان الخاصة بهم) مبلغ 500 دولار أمريكي / يورو نقدًا لشراء تذاكر السفر أو تذاكر القطار للسفر إلى المدينة من وجهتهم ، وكذلك عن النفقات خلال الشهر الأول في روسيا. من المحبط بشدة وضع الأموال والأشياء الثمينة والمستندات في الأمتعة التي تم فحصها ، فمن الضروري حملها في حقائب اليد ومشاهدتها بشكل جيد حتى لا تفقد أي شيء!" : (($lang == 'en') ? "When arriving at the Moscow / St. Petersburg airport, students must have (in addition to their credit card) the amount of 500 USD / Euro in cash to buy air tickets or train tickets to travel to the city of their destination, and also for the expenses during the first month in Russia. It is strongly discouraged to put the money, valuables and documents in the checked luggage, it is necessary to carry them in the hand luggage and to watch them well to lose nothing!" : "En arrivant à l’aéroport de Moscou/St.Pétersbourg, les étudiants doivent avoir (en outre de leur carte bancaire) le montant de 500 USD/Euro en liquide pour acheter les billets d’avion ou de train afin de voyager vers la ville de leur destination, et aussi pour les dépenses pendant le premier mois en Russie. Il est fortement déconseillé de mettre l’argent, des objets précieux et les documents dans le bagage enregistré, il faut les porter dans le bagage à main et les bien surveiller pour ne rien perdre!")); ?></p>
        <p><?php echo (($lang == 'ar') ? "تُدفع تذاكر القطار وتذاكر السفر للرحلات الداخلية بطريقة إضافية (إذا لم يتم تضمين سعر التذكرة في الفاتورة)!" : (($lang == 'en') ? "Train tickets and air tickets for domestic flights are to be paid in an additional way (if the ticket price has not been included in the invoice)!" : "Les billets de train et les billets d’avion pour les vols intérieurs sont à payer d’une manière supplémentaire (si le prix du billet n’a pas été inclus dans la facture)!")); ?></p>
    </div>
    <div class="row">
        <hr class="section-title-line">
        <h2 class="section-title"><?php echo (($lang == 'ar') ? "هل يمكنني الحصول على وظيفة أثناء الدراسة في روسيا؟" : (($lang == 'en') ? "Can I have a job while studying in Russia?" : "Est-ce que je peux avoir un emploi pendant les études en Russie?")); ?></h2>
        <p><?php echo (($lang == 'ar') ? "للعمل في روسيا ، يجب أن يحصل الطلاب الأجانب على الإذن المناسب من المديرية العامة للهجرة في وزارة الداخلية الروسية. الإذن صالح لمدة عام واحد ويجب تجديده لفترة عقد العمل. إذا ترك الطالب المدرسة ، يتم إلغاء الإذن." : (($lang == 'en') ? "To work in Russia, foreign students must have the appropriate permission from the Directorate General of Migration at the Russian Ministry of the Interior. Permission is valid for 1 year and must be renewed for the period of the employment contract. If the student has left school, the permission is canceled." : "Pour travailler en Russie, les étudiants étrangers doivent avoir la permission appropriée de la Direction générale de la migration auprès du Ministère de l’intérieur de Russie. La permission est valable pendant 1 année et elle doit être renouvelée pour la période du contrat du travail. Si l’étudiant a quitté les études, la permission est annulée.")); ?></p>
        <p><?php echo (($lang == 'ar') ? "تم إعداد هذا الإذن لمدة 10 أيام عمل بعد تقديم الملف الكامل إلى الهيئة الإقليمية للمديرية العامة للهجرة في وزارة الداخلية الروسية. يحتوي الملف على:" : (($lang == 'en') ? "This permission is prepared for 10 working days after the submission of the complete file to the territorial body of the Directorate General of Migration at the Russian Ministry of the Interior. The file includes" : "Cette permission est préparée pendant 10 jours ouvriers après le dépôt du dossier complet à l’organe territorial de la Direction générale de la migration auprès du Ministère de l’intérieur de Russie. Le dossier comprend:")); ?></p>
        <ul class="list-group">
            <li class="list-group-item"><?php echo (($lang == 'ar') ? "تطبيق" : (($lang == 'en') ? "Request" : "Demande")); ?></li>
            <li class="list-group-item"><?php echo (($lang == 'ar') ? "جواز سفر" : (($lang == 'en') ? "Passport" : "Passeport")); ?></li>
            <li class="list-group-item"><?php echo (($lang == 'ar') ? "بطاقة الهجرة" : (($lang == 'en') ? "Migration card" : "Carte de migration")); ?></li>
            <li class="list-group-item"><?php echo (($lang == 'ar') ? "تأكيد دفع الرسوم (3500 روبل)" : (($lang == 'en') ? "Confirmation of the payment of the charge (3500 rubles)" : "Confirmation du paiement de la charge (3500 roubles)")); ?></li>
            <li class="list-group-item"><?php echo (($lang == 'ar') ? "عقد عمل" : (($lang == 'en') ? "Employment contract" : "Contrat de travail")); ?></li>
            <li class="list-group-item"><?php echo (($lang == 'ar') ? "شهادة تحليل حول مرض الإيدز والأمراض المعدية والإدمان على المخدرات" : (($lang == 'en') ? "Certificate of analysis on AIDS, contagious diseases, narcotic addiction" : "Certificat d’analyse sur SIDA, maladies contagieuses, dépendance aux narcotiques")); ?></li>
            <li class="list-group-item"><?php echo (($lang == 'ar') ? "شهادة من الجامعة تؤكد أنك تقوم بدراستك في الفصل" : (($lang == 'en') ? "Certificate from the University confirming that you are doing your studies in class" : "Certificat de l’Université qui confirme que vous faites vos études en présentiel")); ?></li>
        </ul>
        <p><?php echo (($lang == 'ar') ? "ولكن لا تنتظر حتى يغطي العمل جميع تكاليف الإقامة. الدراسات في الجامعات الروسية صارمة للغاية ، هناك واجب هذا هو السبب في عدم وجود الكثير من وقت الفراغ. يجب أن يكون لدى الوالدين (الرعاة) وسيلة لتغطية التكاليف الكاملة أثناء إقامتك في روسيا كطالب." : (($lang == 'en') ? "But do not wait until the work covers all accommodation costs. Studies at Russian universities are quite rigorous, there is the duty that is why there is not much free time. Parents (sponsors) must have the means to cover the full costs during your stay in Russia as the student." : "Mais il ne faut pas attendre que le travail couvre tous les frais d’hébergement. Les études aux universités russes sont assez rigoureuses, il y a le devoir c’est pourquoi il n’y a pas beaucoup de temps libre. Les parents (sponsors) doivent avoir des moyens pour couvre la totalité des frais pendant votre séjour en Russie en tant que l’étudiant.")); ?></p>
        <p><?php echo (($lang == 'ar') ? "ليس من المرغوب فيه أن يعمل الطلاب في العامين الأولين حيث أنهم لا يتحدثون اللغة الروسية على المستوى الكافي وغير معتادين بعد على ظروف البلد الجديد. إن العمل الذي يمكن للطلاب الأجانب العثور عليه في معظم الحالات يكون مؤقتًا وغير متخصص ومتدني الأجر: في المطاعم والمقاهي والفنادق والمحلات التجارية والمعسكرات الصيفية إلخ." : (($lang == 'en') ? "It is not desirable that students work for the first two years as they do not speak Russian at the sufficient level and are not yet accustomed to the conditions of the new country. The work that foreign students can find in most cases is temporary, non-specialized and underpaid: in restaurants, cafes, hotels, shops, summer camps etc." : "Ce n’est pas souhaitable que les étudiants travaillent pendant les deux premières années comme ils ne parlent pas russe au niveau suffisant et ne sont pas encore s’habitués aux conditions du nouveau pays. Le travail que les étudiants étrangers peuvent trouver dans la plupart des cas est temporel, non-spécialisé et sous-payé: dans les restaurants, cafés, hôtels, magasins, camps d’été etc.")); ?></p>
    </div>
    <div class="row">
        <hr class="section-title-line">
        <h2 class="section-title"><?php echo (($lang == 'ar') ? "تأشيرة دراسة" : (($lang == 'en') ? "Study Visa" : "Visa d’études")); ?></h2>
        <p><?php echo (($lang == 'ar') ? "يحصل الطلاب الأجانب الذين يذهبون إلى المدرسة لأول مرة على تأشيرة دراسة بسيطة لمدة 90 يومًا. بعد التخرج في روسيا يُطلب من الطلاب تقديم المستندات لتمديد تأشيرة العمل لمدة 45 يومًا قبل تاريخ انتهاء تأشيرة الدراسة الواحدة وسيكون لديهم تأشيرة دراسة متعددة لمدة عام واحد أكاديمي. في السنوات التالية تمديد تأشيرة الدراسة متعددة المرات (45 يوم عمل قبل تاريخ انتهاء الصلاحية) هي تكلفة الطالب الأجنبي." : (($lang == 'en') ? "Foreign students who come to school for the first time receive a simple study visa for 90 days. After graduation in Russia students are required to file the documents for the extension of the 45-day work visa before the expiry date of the single study visa and they will have the multiple-entry study visa for one year academic. The following years the extension of the multiple-entry study visa (45 working days before the expiry date) is a charge of the foreign student." : "Les étudiants étrangers qui arrivent aux études pour la première fois reçoivent le visa d’études simple pour 90 jours. Après l’arrivée aux études en Russie les étudiants sont obligés de déposer les documents pour la prolongation du visa 45 jours ouvriers avant la date d’expiration du visa d’études simple et ils auront le visa d’études à entrées multiples pour une année académique. Les années suivantes la prolongation du visa d’études à entrées multiples (45 jours ouvriers avant la date d’expiration) est une charge de l’étudiant étranger.")); ?></p>
        <p><?php echo (($lang == 'ar') ? "لإعداد تأشيرة الدراسة متعددة المرات ، يجب أن تكون صلاحية جواز سفر الطالب على الأقل 1.5 سنة من تاريخ إصدار التأشيرة. يجب عدم نسيانها ، وإذا لزم الأمر ، يجب عليها تغيير أو تمديد صلاحية جواز السفر." : (($lang == 'en') ? "To prepare the multiple-entry study visa, the validity of the student's passport must be at least 1.5 years from the date of issue of the visa. It should not be forgotten and if necessary it must change or extend the validity of the passport." : "Pour préparer le visa d’études à entrées multiples il faut que la validité du passeport de l’étudiant soit au minimum 1.5 ans de la date de délivrance du visa. Il ne faut pas l’oublier et en cas de besoin il faut changer ou prolonger la validité du passeport.")); ?></p>
        <p><?php echo (($lang == 'ar') ? "تمديد تأشيرة الدراسة في الوقت المناسب هو تهمة الطالب الأجنبي. في حالة عدم تمديد التأشيرة ، سيدفع الطالب غرامة تصل إلى 5000 روبل أو سيتم ترحيله وسيتم منعه من العودة إلى روسيا للسنوات الخمس القادمة." : (($lang == 'en') ? "The extension of the study visa in time is a charge of the foreign student. In case of non-extension of the visa the student will pay a fine up to 5000 rubles or will be deported and will be prohibited from returning to Russia for the next 5 years." : "La prolongation du visa d’études à temps est une charge de l’étudiant étranger. En cas de non-prolongation du visa l’étudiant paiera une amende jusqu’à 5000 roubles ou sera déporté et aura l’interdiction de revenir en Russie pendant 5 ans suivants.")); ?></p>
    </div>
    <div class="row">
        <hr class="section-title-line">
        <h2 class="section-title"><?php echo (($lang == 'ar') ? "هل يمكنني تغيير الجامعة لمواصلة دراستي؟" : (($lang == 'en') ? "Can I change the university to continue my studies?" : "Est-ce que je peux changer l’université pour y continuer mes études?")); ?></h2>
        <p><?php echo (($lang == 'ar') ? "يمكن تغيير الجامعة إذا كنت تحترم القواعد الأكاديمية والالتزامات المالية." : (($lang == 'en') ? "The change of the university is possible if you respect the academic rules and the financial commitments." : "Le changement de l’université est possible si vous respectez les règles académiques et les engagements financiers. ")); ?></p>
    </div>
    <div class="row">
        <hr class="section-title-line">
        <h2 class="section-title"><?php echo (($lang == 'ar') ? "هل يمكنني البقاء في روسيا والعمل هناك بعد الدراسة في الجامعة؟" : (($lang == 'en') ? "Can I stay in Russia and work there after studying at the University?" : "Est-ce que je peux rester en Russie et y travailler après les études à l’Université?")); ?></h2>
        <p><?php echo (($lang == 'ar') ? "لسوء الحظ ، ليس سهلاً. خلال الدراسات في الجامعة الروسية ، يحصل الطالب الأجنبي على تأشيرة الدراسة التي يتم إصدارها خلال فترة الدراسة. بعد الدراسة في الجامعة لا يمكنك البقاء في روسيا والعثور على وظيفة دون تأشيرة العمل (التي تصدر في حالة الدعوة من صاحب العمل) وبدون تصريح العمل." : (($lang == 'en') ? "Unfortunately, it is not so easy. During studies at the Russian University the foreign student has the study visa which is issued for the period of study. After studying at the University you can not stay in Russia and find a job without the work visa (which is issued in case of the invitation from the employer) and without the work permit." : "Malheureusement, ce n’est pas si facile. Pendant les études à l’Université russe l’étudiant étranger a le visa d’études qui est délivré pour la période d’études. Après les études de l’Université vous ne pouvez pas rester en Russie et trouver un emploi sans le visa du travail (qui est délivré en cas de l’invitation de la part de l’employeur) et sans le permis du travail.")); ?></p>
    </div>
    <div class="row">
        <hr class="section-title-line">
        <h2 class="section-title"><?php echo (($lang == 'ar') ? "هل يمكنني الذهاب إلى مدن / دول أخرى خلال العطلات؟" : (($lang == 'en') ? "Can I go to other cities / countries during holidays?" : "Est-ce que je peux partir dans des autres villes/pays pendant les vacances?")); ?></h2>
        <p><?php echo (($lang == 'ar') ? "خلال العطلة الصيفية والصيفية يمكن للطلاب السفر إلى روسيا أو زيارة بلدان أخرى. لكن لا تنسوا قانون الهجرة الروسي" : (($lang == 'en') ? "During the winter and summer holidays students can travel to Russia or visit other countries. But do not forget the Russian migration legislation" : "Pendant les vacances d’hiver et d’été les étudiants peuvent voyager en Russie ou visiter d’autres pays. Mais n’oubliez pas de la législation migratoire russe:")); ?></p>
        <ul class="list-group">
            <li class="list-group-item"><?php echo (($lang == 'ar') ? "أبلغ الجامعة مسبقاً برحلتك وتحقق من أن تأشيرتك ستظل سارية طوال مدة رحلتك." : (($lang == 'en') ? "Inform the university in advance about your trip and check that your visa will still be valid for the period of your trip." : "Informer l’université d’avance sur votre voyage et vérifier que votre visa restera toujours valable pour la période de votre voyage.")); ?></li>
            <li class="list-group-item"><?php echo (($lang == 'ar') ? "لمدة 3 أيام بعد عنوان العودة إلى جامعة التسجيل المهاجرة - وهذا هو إجراء إلزامي لجميع الأجانب الذين يعيدون الرحلات التي تتم في روسيا أو في الخارج." : (($lang == 'en') ? "For 3 days after the return address to the University for Migratory Registration - this is a mandatory procedure for all foreigners who return trips made in Russia or abroad." : "Pendant 3 jours après le retour s’adresser à l’Université pour l’enregistrement migratoire - c’est une procédure obligatoire pour tous les étrangers qui reviennent des voyages faits en Russie ou à l’étranger.")); ?></li>
        </ul>
    </div>
    <div class="row">
        <hr class="section-title-line">
        <h2 class="section-title"><?php echo (($lang == 'ar') ? "ما هي شهادة المعادلة؟" : (($lang == 'en') ? "What is the Equivalency Certificate?" : "Qu’est-ce que c’est le Certificat d’équivalence?")); ?></h2>
        <p><?php echo (($lang == 'ar') ? "خلال السنة الأولى من الدراسة في الجامعة (الكلية التحضيرية) يجب على الطالب أن ينفق على نفقته الخاصة إجراء معادلة الوثائق التعليمية الأجنبية ويحصل على شهادة التكافؤ من Rosobrnadzor. ويعني تعادل التعليم الأجنبي التأكيد الرسمي لمستوى الدراسة الواردة في الخارج ومنح حائز الوثيقة التعليمية للحقوق الأكاديمية والمهنية وغيرها. يقدم الطالب شهادة التكافؤ هذه في الجامعة حيث أن هذه الوثيقة إلزامية لقبول الطلاب في البرامج الجامعية الأساسية (1-6 سنوات)" : (($lang == 'en') ? "During the first year of study at the University (the preparatory faculty) the student must spend at his own expense the procedure of equivalence of foreign educational documents and receive the Certificate of Equivalence from Rosobrnadzor. The equivalence of foreign education means the official confirmation of the level of study received abroad and the granting to the holder of the educational document of academic, professional and other rights. The student presents this Certificate of Equivalence at the University as this document is mandatory for admission of students to basic university programs (1-6 years)" : "Pendant la première année d’études à l’Université (la faculté préparatoire) l’étudiant doit passer à ses frais la procédure d’équivalence des documents éducatifs étrangers et recevoir le Certificat d’équivalence auprès de Rosobrnadzor. L’équivalence de l’éducation étrangère signifie la confirmation officielle du niveau d’études réçu à l’étranger et l’octroi au titulaire du document éducatif des droits académiques, professionnels et autres. L’étudiant présente ce Certificat d’équivalence à l’Université comme ce document est obligatoire pour l’admission des étudiants aux programmes universitaires de base (1-6 années)")); ?></p>
    </div>
    <div class="row">
        <hr class="section-title-line">
        <h2 class="section-title"><?php echo (($lang == 'ar') ? "ما هي الوجبة الروسية؟" : (($lang == 'en') ? "What is the Russian meal?" : "C’est quoi, le repas russe?")); ?></h2>
        <p><?php echo (($lang == 'ar') ? "يوجد في كل طابق من كل منزل بالجامعة مطبخ حيث يمكنك إعداد الوجبة التي تريدها. مجموعة كبيرة من المنتجات من جميع أنحاء العالم ممثلة في المتاجر الروسية تسمح لأكل المنتجات المعتادة. من المفيد معرفة كيفية تحضير الوجبة قبل الوصول إلى روسيا خاصة الأطباق الوطنية." : (($lang == 'en') ? "On every floor of every university home there is a kitchen where you can prepare the meal you want. A large selection of products from all over the world represented in Russian stores allows to eat the usual products. It is useful to know how to prepare the meal before arrival in Russia especially the national dishes." : "Sur chaque étage de tous les foyers universitaires il y a une cuisine où vous pouvez préparer le repas que vous voulez. Un grand choix des produits du monde entier représenté dans les magasins russes permet de manger les produits habituels. Il est utile de savoir préparer le repas avant l’arrivée en Russie en particulier les plats nationaux.")); ?></p>
        <p><?php echo (($lang == 'ar') ? "متوسط ​​الاعتمادات للنظام الغذائي للطالب 200-200 دولار في الشهر." : (($lang == 'en') ? "The average dependencies for the student's diet are 200-300 US $ per month." : "Les dépendes moyennes pour l’alimentation de l’étudiant sont de 200-300 dollars américains par mois.")); ?></p>
        <p><?php echo (($lang == 'ar') ? "يمكن للطالب أيضا حضور المقاهي الطلابية التي ليست باهظة الثمن ، ومتوسط ​​تكلفة غداء الطلاب (حساء ، الطبق الرئيسي المزين ، سلطة ، شاي) هو 3-5 دولارات أمريكية." : (($lang == 'en') ? "The student can also attend student cafes that are not expensive, the average cost of student lunch (soup, main course garnished, salad, tea) is 3-5 US dollars." : "L’étudiant peut aussi fréquenter les cafés étudiants qui ne sont pas chers, le coût moyen du déjeuner étudiant (soupe, plat principal garni, salade, thé) est de 3-5 dollars américains.")); ?></p>
    </div>
</div>

<div class="section universities">
    <div class="row">
        <hr class="section-title-line">
        <h2 class="section-title"><?php echo (($lang == 'ar') ? "السكن الجامعي" : (($lang == 'en') ? "UNIVERSITY ACCOMMODATION" : "HÉBERGEMENT UNIVERSITAIRE")); ?></h2>
    </div>
    <div class="row">
        <p><?php echo (($lang == 'ar') ? "خيار رخيص وجيد للطلاب الجدد القادمين ، التي تقدمها الجامعة. تختلف الأسعار وفقًا للأولويات الخاصة بك ، ويعود الأمر تمامًا إلى اختيارك ويسأل عما تحب وما الذي يجعلك مرتاحًا. عادة ، نوصي بالعيش في النزل للطلاب الجدد." : (($lang == 'en') ? "Cheap and good option for new upcoming students, provided by the University. Prices vary according to your own priorities, it is totally up to your choice and asks what you like and what makes you comfortable. Normally, we recommend living in the hostel for new students to come." : "Option pas cher et bon pour les nouveaux étudiants à venir, fournies par l’Université. Les prix varient en fonction de vos propres priorités, il est totalement à votre choix et la demande ce que vous aimez et ce qui vous rend le confort. Normalement, nous recommandons de vivre dans l’auberge pour les nouveaux étudiants à venir.")); ?></p>
        <p><?php echo (($lang == 'ar') ? "لأن" : (($lang == 'en') ? "Because;" : "Parce que;")); ?></p>
        <p><?php echo (($lang == 'ar') ? "إنهم لا يعرفون لغة التواصل مع السكان." : (($lang == 'en') ? "They do not know the language of communication with the inhabitants." : "Ils ne savent pas la langue de communication avec les habitants.")); ?></p>
        <p><?php echo (($lang == 'ar') ? "إنهم لا يعرفون جذور الحافلات في المدينة خارج الحرم الجامعي." : (($lang == 'en') ? "They do not know the city's bus roots outside the university campus." : "Ils ne savent pas les racines de bus de la ville à l’extérieur du campus universitaire.")); ?></p>
        <p><?php echo (($lang == 'ar') ? "نحن نساعد الطالب طوال الوقت ، لكن إذا كانوا يعيشون خارج الحرم الجامعي فلا يمكننا الاقتراب منهم ، لذلك من الصعب مساعدتهم." : (($lang == 'en') ? "We help the student throughout, but if they live outside the university campus we can not approach them, so it is difficult to help them." : "Nous aidons l’étudiant tout au long mais si ils vivent en dehors du campus universitaire nous ne pouvons pas les approcher, il est donc difficile de les aider.")); ?></p>
        <p><?php echo (($lang == 'ar') ? "الحرم الجامعي هو أفضل مكان للقاء أشخاص جدد واكتساب تجارب جديدة وتكوين صداقات جديدة تعيش مدى الحياة." : (($lang == 'en') ? "The university campus is the best place to meet new people, gain new experiences and make new friends who live for life." : "Le campus universitaire est le meilleur endroit pour rencontrer de nouvelles personnes, acquérir de nouvelles expériences et faire de nouveaux amis qui vit pour la vie.")); ?></p>
        <p><?php echo (($lang == 'ar') ? "<span class='alert alert-danger'>ملاحظة :</span>  يمكن استيعاب الطلاب الأجانب في منازل الطلاب ، ولكن يمكنك أيضًا العثور على شقق للإيجار." : (($lang == 'en') ? "<span class='alert alert-danger'>NB :</span> Foreign students can be accommodated in student homes, but you can also find apartments for rent." : "<span class='alert alert-danger'>NB :</span> Les étudiants étrangers peuvent être logés dans des foyers d’étudiants, mais ils peuvent également, trouver des appartements à louer.")); ?></p>
    </div>
    <!-- <div class="row">
        <hr class="section-title-line">
        <h2 class="section-title"><?php echo (($lang == 'ar') ? "الإقامة في أوكرانيا وروسيا." : (($lang == 'en') ? "Accommodation in Ukraine and Russia." : "Hébergement en Ukraine et en Russie.")); ?></h2>
    </div>
    <div class="row">
        
        <p><?php echo (($lang == 'ar') ? "الإقامة في أوكرانيا وروسيا هي أرخص وفقا لدول أوروبية أخرى ، الأسعار تختلف وفقا لأولوياتك الخاصة ، الأمر متروك تماما لاختيارك والمطالبة بما تحبه وما يجعلك مرتاحا. عادة ، نوصي بالعيش في بيت الشباب للطلاب الجدد." : (($lang == 'en') ? "Accommodation in Ukraine and Russia are cheaper according to other European states, prices vary according to your own priorities, it is totally up to your choice and demand what you like and what makes you comfortable. Normally, we recommend living in the hostel for new students to come." : "Hébergement en Ukraine et en Russie sont moins cher selon les autres États européens, les prix varient en fonction de vos propres priorités, il est totalement à votre choix et la demande ce que vous aimez et ce qui vous rend le confort. Normalement, nous recommandons de vivre dans l’auberge pour les nouveaux étudiants à venir.")); ?></p>
        <p><?php echo (($lang == 'ar') ? "لأن" : (($lang == 'en') ? "Because;" : "Parce que;")); ?></p>
        <p><?php echo (($lang == 'ar') ? "انهم لا يعرفون لغة التواصل مع السكان" : (($lang == 'en') ? "They do not know the language of communication with the inhabitants" : "Ils ne savent pas la langue de communication avec les habitants")); ?></p>
        <p><?php echo (($lang == 'ar') ? "انهم لا يعرفون جذور الحافلة في المدينة خارج حرم الجامعة" : (($lang == 'en') ? "They do not know the city's bus roots outside the university campus" : "Ils ne savent pas les racines de bus de la ville à l’extérieur du campus universitaire")); ?></p>
        <p><?php echo (($lang == 'ar') ? "نساعد الطالب طوال الوقت ، ولكن إذا كانوا يعيشون خارج حرم الجامعة ، لا يمكننا الاقتراب منهم ، لذلك من الصعب مساعدتهم." : (($lang == 'en') ? "We help the student throughout, but if they live outside the university campus we can not approach them, so it is difficult to help them." : "Nous aidons l’étudiant tout au long mais si ils vivent en dehors du campus universitaire nous ne pouvons pas les approcher, il est donc difficile de les aider.")); ?></p>
        <p><?php echo (($lang == 'ar') ? "حرم الجامعة هو أفضل مكان للقاء أشخاص جدد واكتساب خبرات جديدة وتكوين صداقات جديدة تعيش مدى الحياة." : (($lang == 'en') ? "The university campus is the best place to meet new people, gain new experiences and make new friends who live for life." : "Le campus universitaire est le meilleur endroit pour rencontrer de nouvelles personnes, acquérir de nouvelles expériences et faire de nouveaux amis qui vit pour la vie.")); ?></p>
    </div>
    <div class="row">
        <hr class="section-title-line">
        <h2 class="section-title"><?php echo (($lang == 'ar') ? "السكن الجامعي" : (($lang == 'en') ? "UNIVERSITY ACCOMMODATION" : "HÉBERGEMENT UNIVERSITAIRE")); ?></h2>
    </div>
    <div class="row">
        <p><?php echo (($lang == 'ar') ? "خيار رخيص وجيد للطلاب الجدد القادمين ، مقدم من الجامعة." : (($lang == 'en') ? "Cheap and good option for new upcoming students, provided by the University." : "Option pas cher et bon pour les nouveaux étudiants à venir, fournies par l’Université.")); ?></p>
        <p><?php echo (($lang == 'ar') ? "الغرفة من شخصين إلى ثلاثة أشخاص: رسوم مكان واحد - 1000 دولار - 1200 دولار مع تجديد ممتاز (يشمل جميع المعدات اللازمة للعيش في سهولة)." : (($lang == 'en') ? "The room of two to three people: one place charges - $ 1000- $ 1200 with excellent renovation (includes all the necessary equipment to live at ease)." : "La chambre de deux à trois personnes: charges d’une place – 1000 $-1200 $ avec une excellent rénovation (comprend tous les équipements nécessaires pour vivre à l’aise).")); ?></p>
        <p><?php echo (($lang == 'ar') ? "يتم تصنيف تكاليف الشقة وفقا لمساحتها ، وحالتها ومكانها." : (($lang == 'en') ? "The costs of the apartment are classified according to their space, their state and their place." : "Les frais de l’appartement sont classés selon leur espace, leur état et leur lieu.")); ?></p>
        <p><?php echo (($lang == 'ar') ? "<span class='alert alert-danger'>ملاحظة :</span>  يمكن استيعاب الطلاب الأجانب في منازل الطلاب ، ولكن يمكنك أيضًا العثور على شقق للإيجار." : (($lang == 'en') ? "<span class='alert alert-danger'>NB :</span> Foreign students can be accommodated in student homes, but you can also find apartments for rent." : "<span class='alert alert-danger'>NB :</span> Les étudiants étrangers peuvent être logés dans des foyers d’étudiants, mais vous pouvez également, trouver des appartements à louer.")); ?></p>
    </div> -->
</div>

<?php include $path.'/layouts/sidebar.php'; ?>
<?php include $path.'/layouts/footer.php';
footer(); ?>