<?php $path = $_SERVER['DOCUMENT_ROOT'] . "/rae.ma";
    include $path.'/layouts/header.php'  ;
    $title = get_lang_text("الدراسات العليا في أوكرانيا","Graduate studies in Ukraine","Les études supérieures en Ukraine");
    title_page($title,3)
?>


<?php include $path.'/layouts/feature.php';
    $txt = "Les études supérieures en Ukraine";
    if(isset($_GET['lang'])){
        $txt = translate_feature_txt("Les études supérieures en Ukraine", "الدراسات العليا في أوكرانيا", "Graduate studies in Ukraine");
    }
    feature_txt($txt, "ukraine");
?>

<div class="sup-study">
    <div class="">
        <div class="section sup-study-uk">
            <div class="">
                <div class="row">
                    <hr class="section-title-line">
                    <h2 class="section-title"><?php echo (($lang == 'ar') ? "الدراسات العليا في أوكرانيا" : (($lang == 'en') ? "Graduate studies in Ukraine" : "Les études supérieures en Ukraine")); ?></h2>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <p><?php echo (($lang == 'ar') ? "خلال سنوات عديدة من التنمية وعمل عاطفي من العلماء، وقد بنيت أوكرانيا نظام التعليم الوطني الكبير، كما يدل على ذلك انضمام أوكرانيا إلى الفضاء التعليمي الأوروبية والعالمية، وذلك بفضل عملية بولونيا.
                        الآن، وقد أتاحت الفرص التعليمية من أوكرانيا البلاد لتصبح واحدة من الدول الرائدة 10 في مجال التعليم الدولي، كما يتضح من الاهتمام الكبير من الطلاب الدوليين في مجال التعليم العالي في اوكرانيا.
                        تقدم مؤسسات التعليم العالي الأوكرانية دورات في اللغة الأوكرانية أو الروسية أو الإنجليزية. لدى الطلاب الدوليين الفرصة للدراسة في أكثر من 240 مؤسسة للتعليم العالي وللتخصص في المجالات العلمية المختلفة. في كل عام ، ترحب مؤسسات التعليم العالي بالطلاب من أكثر من 150 دولة. يمكن لجميع المؤسسات التعليمية توفير التعليم لجميع أنواع البرامج التدريبية وفقا للقانون الأوكراني «في التعليم العالي»." : (($lang == 'en') ? "Thanks to many years of development and the passionate work of scientists, Ukraine has built a great national education system, as evidenced by the accession of Ukraine to the European and global educational space, thanks to the Bologna Process.
                        For the moment, Ukraine's educational opportunities have enabled it to become one of the top 10 countries in the field of international education, as evidenced by the high interest of international students in higher education. in Ukraine.
                        Ukrainian higher education institutions offer courses in Ukrainian, Russian or English. International students have the opportunity to study in more than 240 higher education institutions and to specialize in different scientific fields. Each year, higher education institutions welcome students from more than 150 countries. All educational institutions can provide education for all types of training programs in accordance with the Ukrainian Law «On Higher Education»." : "Grâce à de nombreuses années de développement et au travail passionné des scientifiques, l'Ukraine a construit un grand système éducatif national, comme le prouve l'adhésion de l'Ukraine à l'espace éducatif européen et mondial, grâce au processus de Bologne.
                        Pour le moment, les possibilités d’éducation de l’Ukraine ont permis à ce pays de devenir l’un des 10 pays leaders dans le domaine de l’éducation internationale, comme le prouve le grand intérêt des étudiants internationaux pour l’enseignement supérieur en Ukraine. 
                        Les établissements d’enseignement supérieur ukrainiens dispensent des cours en ukrainien, en russe ou en anglais. Les étudiants internationaux ont la possibilité d'étudier dans plus de 240 établissements d'enseignement supérieur et de se spécialiser dans différents domaines scientifiques. Chaque année, les établissements d’enseignement supérieur accueillent des étudiants de plus de 150 pays. Tous les établissements d'enseignement peuvent dispenser un enseignement pour tous les types de programmes de formation conformément à la loi ukrainienne «sur l'enseignement supérieur».")); ?></p>
                    </div>
                </div>            
            </div>
        </div>
        <div class="section degrees">
            <div class="">
                <div class="row">
                    <hr class="section-title-line">
                    <h2 class="section-title"><?php echo (($lang == 'ar') ? "تقدم الجامعات الأوكرانية النقاط التالية:" : (($lang == 'en') ? "UKRAINIAN UNIVERSITIES PROVIDE THE FOLLOWING DEGREES:" : "LES UNIVERSITÉS UKRAINIENNES FOURNISSENT LES DEGRÉS SUIVANTS: ")); ?></h2>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <ul class="list-group">
                            <li class="list-group-item"><?php echo (($lang == 'ar') ? "الترخيص. يتم الترخيص على أساس التعليم الثانوي العام الكامل. مدة الدراسات 4 سنوات. يحصل الخريجين الذين يجتازون امتحانات الدولة على درجة البكالوريوس التي تمنحهم الحق في العمل في المهنة المدروسة والحق في قبولهم في برنامج الماجستير." : (($lang == 'en') ? "Licence . Licensing is done on the basis of full general secondary education. The duration of studies is 4 years. Graduates who pass the state exams obtain a bachelor's degree which gives the right to work to the profession studied and the right to be admitted to the master's program." : "Licence . La préparation des licences se fait sur la base de l’enseignement secondaire général complet. La durée des études est de 4 ans. Les diplômés qui réussissent les examens d’État obtiennent un baccalauréat qui donne le droit de travailler à la profession étudiée et le droit d’être admis au programme de master.")); ?></li>
                            <li class="list-group-item"><?php echo (($lang == 'ar') ? "الرئيسية. دراسات الماجستير ممكنة على أساس درجة البكالوريوس. فترة الدورة هي 1-2 سنوات. يجتاز الخريجون شهادة الولاية ، والتي تتضمن عرضًا عامًا للكتاب. يحصل من يجتازون شهادة الدولة على درجة الماجستير التي تمنحهم الحق في العمل في المهنة والحق في قبولهم في قسم الدراسات العليا." : (($lang == 'en') ? "Master. Master's studies are possible on the basis of a bachelor's degree. The period of the course is 1-2 years. Graduates pass state certification, which includes a public presentation of the book. Those who pass the state certification obtain a Master degree that gives the right to work in the profession and the right to be admitted to the graduate department." : "Master. Les études de maîtrise sont possibles sur la base d'un baccalauréat. La période du cours est de 1-2 ans. Les diplômés passent la certification d’État, qui comprend une présentation publique de l’ouvrage. Les personnes qui réussissent la certification d’Etat obtiennent un Master qui donne le droit de travailler dans la profession et le droit d’être admis au département d’études supérieures.")); ?></li>
                            <li class="list-group-item"><?php echo (($lang == 'ar') ? "الدكتوراه. درجة الدكتوراه هي درجة علمية يتم تلقيها في نهاية دورة الدراسات العليا. يمكن قبول الشخص الحاصل على درجة الماجستير في قسم الدراسات العليا بالجامعة. الحصول على الدكتوراه ينطوي على عرض عام للرسالة." : (($lang == 'en') ? "PhD. A PhD is a scientific degree received at the end of the post-graduate course. A person with a masters qualification can be admitted to the graduate department of the university. Obtaining the doctorate involves a public presentation of the thesis." : "PhD . Un doctorat est un diplôme scientifique reçu à la fin du cursus post-gradué. Une personne ayant une qualification de maîtrise peut être admise dans le département de troisième cycle de l'université. L'obtention du doctorat implique une présentation publique de la thèse.")); ?></li>
                            <li class="list-group-item"><?php echo (($lang == 'ar') ? "الحصول على كل هذه الشهادات العلمية والتعليم العالي ينطوي على اكتساب المعرفة النظرية الفردية والمهارات والخبرات الكافية لتوليد أفكار جديدة، حل المشاكل المعقدة من خلال الأنشطة المهنية أو البحث ." : (($lang == 'en') ? "Obtaining all these degrees of higher and scientific education involves the acquisition of individual theoretical knowledge, skills and other skills sufficient to generate new ideas, solve complex problems in the context of professional activities or research ." : "L'obtention de tous ces diplômes d'enseignement supérieur et scientifique implique l'acquisition de connaissances théoriques individuelles, de compétences et d'autres compétences suffisantes pour générer de nouvelles idées, résoudre des problèmes complexes dans le cadre d'activités professionnelles ou de recherche.")); ?></li>
                            <li class="list-group-item"><?php echo (($lang == 'ar') ? "أوكرانيا ، وهي دولة أوروبية تبلغ نسبة محو الأمية فيها 99.5٪ ، هي أفضل مكان للدراسة في العالم. الجامعات الأوكرانية هي بالتأكيد أفضل خيار وأفضل خيار لأي طالب يرغب في متابعة التعليم العالي والراغبين في مهنة ناجحة." : (($lang == 'en') ? "Ukraine, a European country with 99.5% literacy, is the best place to study in the world. Ukrainian universities are certainly the best choice and the best choice for any student wishing to pursue higher education and wishing a successful career." : "L'Ukraine, pays européen à 99,5% d'alphabétisme, est le meilleur endroit pour étudier dans le monde. Les universités ukrainiennes sont certainement le meilleur choix et le meilleur choix pour tout étudiant souhaitant poursuivre des études supérieures et souhaitant une carrière réussie.")); ?></li>
                        </ul>
                    </div>
                </div>
                <div class="row">
                    <hr class="section-title-line">
                    <h2 class="section-title"><?php echo (($lang == 'ar') ? "MBBS في أوكرانيا" : (($lang == 'en') ? "MBBS IN UKRAINE" : "MBBS EN UKRAINE ")); ?></h2>
                </div>
                <div class="row paths">
                    <div class="col-md-12">
                        <p><?php echo (($lang == 'ar') ? "بصفته طالبًا طبًا في أوكرانيا ، يستفيد الطلاب من جودة التدريس العالية في بعض الجامعات ، مع رسوم التعليم وتكلفة المعيشة غير المكلفة. معظم الجامعات الطبية الاوكرانية التي تدرس الطب (MBBS / MD)، وطب الأسنان، والتمريض، والصيدلة، وما إلى ذلك، لديها أكثر من 20 عاما من الخبرة في مجال التعليم الطبي باللغة الإنجليزية أو الفرنسية ." : (($lang == 'en') ? "As a medical student in Ukraine, students benefit from the high quality of teaching in some universities, with tuition fees and an inexpensive cost of living. Most of the Ukrainian medical universities that teach medicine (MBBS / MD), dentistry, nursing, pharmacy, etc., have more than 20 years of experience in teaching medicine in English or French ." : "Etudiant en médecine en Ukraine, les étudiants bénéficient de la haute qualité de l'enseignement dans certaines universités, avec des frais de scolarité et un coût de la vie peu coûteux. La plupart des universités de médecine ukrainiennes qui enseignent la médecine (MBBS / MD), la dentisterie, les soins infirmiers, la pharmacie, etc., ont plus de 20 ans d'expérience dans l'enseignement de la médecine en anglais ou en français.")); ?></p>
                        <p><?php echo (($lang == 'ar') ? "يدخل آلاف الطلاب الدوليين من أكثر من 110 دولة مختلفة التعليم العالي في أوكرانيا اليوم وينجذب العديد منهم للدراسات الطبية. معظمهم يأتون من الهند ونيجيريا والصين وتركيا وأوغندا وروسيا وماليزيا ودول أوروبا الوسطى. تتعاون المؤسسات الطبية الأوكرانية عن كثب مع الجامعات الألمانية والفرنسية والإيطالية والبولندية والبريطانية والأمريكية والنمساوية ؛ يسمح هذا للطلاب بالمشاركة في المؤتمرات الدولية وبرامج التبادل ومختلف المشاريع العلمية." : (($lang == 'en') ? "Thousands of international students from more than 110 different countries enter tertiary education in Ukraine today and many of them are attracted to medical studies. Most of them come from India, Nigeria, China, Turkey, Uganda, Russia, Malaysia and Central European countries. Ukrainian medical institutions cooperate closely with German, French, Italian, Polish, British, American and Austrian universities; This allows students to participate in international conferences, exchange programs and various scientific projects." : "Des milliers d'étudiants internationaux de plus de 110 pays différents entrent dans l'enseignement supérieur en Ukraine aujourd'hui et une bonne partie d'entre eux sont attirés par les études de médecine. La plupart d'entre eux viennent d'Inde, du Nigeria, de Chine, de Turquie, d'Ouganda, de Russie, de Malaisie et de pays d'Europe centrale. Les établissements médicaux ukrainiens coopèrent étroitement avec des universités allemandes, françaises, italiennes, polonaises, britanniques, américaines et autrichiennes; Cela permet aux étudiants de participer à des conférences internationales, à des programmes d'échange et à divers projets scientifiques.")); ?></p>
                    </div>
                </div>
                
                <div class="row">
                    <hr class="section-title-line">
                    <h2 class="section-title"><?php echo (($lang == 'ar') ? "دراسة الطب في أوكرانيا: البرامج الطبية" : (($lang == 'en') ? "STUDYING MEDICINE IN UKRAINE: MEDICAL PROGRAMS" : "ÉTUDIER LA MÉDECINE EN UKRAINE: PROGRAMMES MÉDICAUX")); ?></h2>
                </div>
                <div class="row paths">
                    <div class="col-md-12">
                        <h3><?php echo (($lang == 'ar') ? "الدورات الطبية الأكثر شعبية بين الطلاب الدوليين في أوكرانيا هي:" : (($lang == 'en') ? "The most popular medical courses among international students in Ukraine are:" : "Les cours de médecine les plus populaires parmi les étudiants internationaux en Ukraine sont:")); ?></h3>
                        <ul class="list-group">
                            <li class="list-group-item"><?php echo (($lang == 'ar') ? "الطب: مدة الدورة الطبية 6 سنوات. الدرجة الممنوحة هي طبيب (MD أو MBBS) ؛" : (($lang == 'en') ? "Medicine: the duration of the medical course is 6 years; the degree awarded is a medical doctor (MD or MBBS);" : "Médecine: la durée du cours de médecine est de 6 ans; le diplôme délivré est un docteur en médecine (MD ou MBBS);")); ?></li>
                            <li class="list-group-item"><?php echo (($lang == 'ar') ? "طب الأسنان: مدة دورة طبيب الأسنان هي 5 سنوات ؛ الدبلوم الممنوح هو بكالوريوس طب الأسنان (BDS) ؛" : (($lang == 'en') ? "Dental: the duration of the dentist course is 5 years; Diploma awarded is a Bachelor of Dental Medicine (BDS);" : "Dentaire: la durée du cours de dentiste est de 5 ans; diplôme délivré est un baccalauréat en médecine dentaire (BDS);")); ?></li>
                            <li class="list-group-item"><?php echo (($lang == 'ar') ? "طب الأطفال: مدة الدورة 6 سنوات ؛ درجة تمنح دواء طب (طبيب أطفال) ؛" : (($lang == 'en') ? "Pediatrics: the duration of the course is 6 years; degree awarded is a doctor of medicine (pediatrician);" : "Pédiatrie: la durée du cours est de 6 ans; diplôme délivré est docteur en médecine (pédiatre);")); ?></li>
                            <li class="list-group-item"><?php echo (($lang == 'ar') ? "التمريض: مدة الدورة 4 سنوات ؛ درجة الحائز على بكالوريوس العلوم في التمريض." : (($lang == 'en') ? "Nursing: the duration of the course is 4 years; degree awarded is Bachelor of Science in Nursing." : "Soins infirmiers: la durée du cours est de 4 ans; diplôme décerné est baccalauréat en sciences infirmières.")); ?></li>
                            <li class="list-group-item"><?php echo (($lang == 'ar') ? "الدراسات العليا: مدة الدراسة 2 إلى 3 سنوات" : (($lang == 'en') ? "Dental orthopedics: the duration of the course is 2 years; the diploma obtained is a bachelor's degree in dental orthopedics;" : "Orthopédie dentaire: la durée du cours est de 2 ans; le diplôme obtenu est un baccalauréat en orthopédie dentaire;")); ?></li>
                            <li class="list-group-item"><?php echo (($lang == 'ar') ? "الدراسات العليا: مدة الدراسة 2 إلى 3 سنوات" : (($lang == 'en') ? "Postgraduate studies: the duration of the study is 2 to 3 years" : "Études post-universitaires: la durée de l'étude est de 2 à 3 ans")); ?></li>
                        </ul>
                    </div>
                </div>
                
                <div class="row">
                    <hr class="section-title-line">
                    <h2 class="section-title"><?php echo (($lang == 'ar') ? "مزايا دراسة MBBS الأوكرانية" : (($lang == 'en') ? "ADVANTAGES OF MBBS UKRAINE STUDY" : "AVANTAGES DE L'ETUDE DE MBBS EN UKRAINE")); ?></h2>
                </div>
                <div class="row paths">
                    <div class="col-md-12">
                        <h3><?php echo (($lang == 'ar') ? "الدورات الطبية الأكثر شعبية بين الطلاب الدوليين في أوكرانيا هي:" : (($lang == 'en') ? "The most popular medical courses among international students in Ukraine are:" : "Les cours de médecine les plus populaires parmi les étudiants internationaux en Ukraine sont:")); ?></h3>
                        <ul class="list-group">
                            <li class="list-group-item"><?php echo (($lang == 'ar') ? "درجة الحصول عليها في أوكرانيا صالحة مباشرة في 27 دولة أوروبية لأن أوكرانيا هي عضو في عملية بولونيا. لذلك ، يمكنك أن تقلق بشأن معايير الجودة في درجة MBBS المقدمة في أوكرانيا." : (($lang == 'en') ? "The degree obtained in Ukraine is directly valid in 27 European countries because Ukraine is a member of BOLOGNA PROCESS. Therefore, you can worry about the quality standards of the MBBS degree provided in Ukraine." : "Le diplôme obtenu en Ukraine est directement valable dans 27 pays européens car l’Ukraine est membre de BOLOGNA PROCESS. Par conséquent, vous pouvez vous inquiéter des normes relatives à la qualité du diplôme MBBS fourni en Ukraine.")); ?></li>
                            <li class="list-group-item"><?php echo (($lang == 'ar') ? "يتم التعرف على دورات MBBS في الجامعات الأوكرانية على مستوى العالم من قبل منظمة الصحة العالمية ، MCI ، اليونسكو ، المجلس الأوروبي ، إلخ." : (($lang == 'en') ? "MBBS courses in Ukrainian universities are globally recognized by the WHO, the MCI, UNESCO, the European Council, etc." : "Les cours MBBS dans les universités ukrainiennes sont mondialement reconnus par l'OMS, le MCI, l'UNESCO, le Conseil européen, etc.")); ?></li>
                            <li class="list-group-item"><?php echo (($lang == 'ar') ? "تعتبر أوكرانيا دولة أوروبية تتمتع بمستويات معيشة أوروبية ، لكن تكاليف التعليم والتدريب منخفضة للغاية مقارنة بالدول الأوروبية الأخرى." : (($lang == 'en') ? "Ukraine is a European country with European standards of living, but tuition and training costs are very low compared to other European countries." : "L’Ukraine est un pays européen qui a les normes de vie européennes mais les frais de scolarité et les frais de formation sont très bas par rapport aux autres pays européens. ")); ?></li>
                            <li class="list-group-item"><?php echo (($lang == 'ar') ? "دورات MBBS في أوكرانيا هي أيضا باللغة الإنجليزية. لذلك ، يمكن للطلاب المغاربة الذين يتقنون اللغة الإنجليزية فقط دراسة MBBS بسهولة في أوكرانيا. حتى الناس هنا يتحدثون اللغة الإنجليزية وليس هناك مشكلة في الإقامة في أوكرانيا." : (($lang == 'en') ? "MBBS courses in Ukraine are also in English. Therefore, Moroccan students who only master English can easily study MBBS in Ukraine. Even people here speak English and there is no problem residing in Ukraine." : "Les cours MBBS en Ukraine sont également en anglais. Par conséquent, les étudiants marocains qui ne maîtrisent que l'anglais peuvent facilement étudier MBBS en Ukraine. Même les gens ici parlent anglais et il n’ya aucun problème à résider en Ukraine.")); ?></li>
                            <li class="list-group-item"><?php echo (($lang == 'ar') ? "المناخ معتدل أيضًا ، لذا لن يواجه الطلاب مشكلة في الاستقرار في المدن الأوكرانية." : (($lang == 'en') ? "The climate is also moderate, so that students will have no problem settling in Ukrainian cities." : "Le climat est également modéré, de sorte que les étudiants n’auront aucun problème à s’installer dans des villes ukrainiennes.")); ?></li>
                            <li class="list-group-item"><?php echo (($lang == 'ar') ? "لا يوجد ILETS و TOEFL المطلوبة." : (($lang == 'en') ? "No ILETS and TOEFL required." : "Aucun ILETS et TOEFL requis. ")); ?></li>
                            <li class="list-group-item"><?php echo (($lang == 'ar') ? "خفضت MBBS في أوكرانيا رسوم التعليم الأسترالية الجامعات MBBS حضور دورات المستوى الرفيع ، ويعمل بها معلمين مؤهلين." : (($lang == 'en') ? "MBBS in Ukraine has reduced tuition fees Ukrainian MBBS universities attend high level courses and are staffed by qualified teachers." : "MBBS en Ukraine a des frais de scolarité réduits Les universités MBBS ukrainiennes suivent des formations de haut niveau et sont dotées d'enseignants qualifiés.")); ?></li>
                            <li class="list-group-item"><?php echo (($lang == 'ar') ? "لا توجد اختبارات القبول." : (($lang == 'en') ? "There are no admission tests." : "Il n’existe pas de tests d’admission.")); ?></li>
                            <li class="list-group-item"><?php echo (($lang == 'ar') ? "بما أن أوكرانيا جزء من عملية بولونيا ، فإن معايير وجودة التعليم هي بنفس مستوى المعايير الدولية." : (($lang == 'en') ? "Since Ukraine is part of the BOLOGNA process, the standards and quality of education are at the same level as international standards." : "L’Ukraine faisant partie du processus BOLOGNA, les normes et la qualité de l’éducation sont au même niveau que les normes internationales. ")); ?></li>
                            <li class="list-group-item"><?php echo (($lang == 'ar') ? "الجامعات الأوكرانية لديها مرتبة عالمية جيدة والدبلومات ستكون متاحة ومعترف بها." : (($lang == 'en') ? "Ukrainian universities have a good world ranking and diplomas will be available and recognized." : "Les universités ukrainiennes ont un bon classement mondial et les diplômes seront disponibles et reconnus.")); ?></li>
                            <li class="list-group-item"><?php echo (($lang == 'ar') ? "تقريبا جميع الجامعات الطبية في أوكرانيا معترف بها من قبل منظمة الصحة العالمية ، FAIMER ، IMED <اليونسكو ، الخ." : (($lang == 'en') ? "Almost all the medical universities of Ukraine are recognized by WHO, FAIMER, IMED <UNESCO, etc." : "Presque toutes les universités de médecine de l’Ukraine sont reconnues par l’OMS, FAIMER, IMED < UNESCO, etc.")); ?></li>
                            <li class="list-group-item"><?php echo (($lang == 'ar') ? "يمكن للطلاب إكمال MBBS في أوكرانيا وبعد. ويمكنهم ممارسة الطب في أي بلد بعد اجتياز امتحانات الترخيص واجتيازها مثل USMLE ، و PLAM للمملكة المتحدة ، و MCI للهند وغيرها." : (($lang == 'en') ? "Students can complete their MBBS in Ukraine and after. They can practice medicine in any country after passing and passing the licensing exams like USMLE for the United States, PLAM for the UK, MCI for India and others." : "Les étudiants peuvent compléter leur MBBS en Ukraine et après. Ils peuvent pratiquer la médecine dans n’importe quel pays après avoir passé et réussi les examens de licence comme USMLE pour les États-Unis, PLAM pour le Royaume-Uni, MCI pour l’Inde et autres. ")); ?></li>
                            <li class="list-group-item"><?php echo (($lang == 'ar') ? "تركز الدورات على التطوير الكامل للطلاب. تكلفة المعيشة منخفضة أيضا في أوكرانيا ، لذلك لن يكلف الكثير." : (($lang == 'en') ? "The courses are focused on the complete development of students. The cost of living is also low in Ukraine, so it will not cost much." : "Les cours sont ciblés sur le développement complet des étudiants. Le coût de la vie étant également faible en Ukraine, il ne coûtera donc pas beaucoup.")); ?></li>
                        </ul>
                    </div>
                </div>
                <p><?php echo (($lang == 'ar') ? "عندما يتعلق الأمر بدراسة الطب الأجنبي باللغة الإنجليزية ، فإن كليات الطب في أوكرانيا هي واحدة من أفضل الوجهات. يتم رسمها طلاب من جميع أنحاء العالم (بريطانيا وألمانيا والدول الاسكندنافية والهند وأفريقيا، الخ) لدراسة الطب (الطب، طب الأسنان، علاج الأرجل، والتمريض، وغيرها) في أوكرانيا بسبب تكاليف المعيشة دراسات طبية منخفضة جدًا ودراسات تعليمية وجودة." : (($lang == 'en') ? "When it comes to studying foreign medicine in English, medical schools in Ukraine are one of the best destinations. Students from all over the world (UK, Germany, Scandinavia, India, Africa, etc.) are attracted to the medical studies (medicine, dentistry, podiatry, nursing, etc.) in Ukraine because of the cost of living very low, tuition and quality medical studies." : "Quand il s'agit d'étudier la médecine à l'étranger en anglais, les écoles de médecine en Ukraine sont l'une des meilleures destinations. Des étudiants du monde entier (Royaume-Uni, Allemagne, Scandinavie, Inde, Afrique, etc.) sont attirés par les études de médecine (médecine, dentisterie, podiatrie, soins infirmiers, etc.) en Ukraine en raison du coût de la vie très bas, des frais de scolarité et de la qualité études de médecine.")); ?></p>
            </div>
        </div>
    </div>
</div>
    

    <?php include $path.'/layouts/sidebar.php'; ?>
<?php include $path.'/layouts/footer.php';
footer(); ?>