
<?php 
    $path = $_SERVER['DOCUMENT_ROOT'];
    include $path.'/layouts/header.php'  ;
    title_page('Sumy State University');
?>


<?php include $path.'/layouts/feature.php';
    feature_txt('Sumy State University', "ukraine");
?>

<div class="post">
    <div class="post-header"><div class="col-sm-12 col-md-12">
        <h2 class="">Sumy State University</h2>
    </div></div>
    <div class="post-img"><img src="/images/universities/ukraine/Sumy-State-University.jpg" alt=""></div>
    <div class="post-txt">
    <p></p><p><strong>Sumy State University</strong>&nbsp;is located in Sumy city in the North-East of Ukraine. Its history began in 1948. Today, SSU is a leading university of a classical type with the III-IV accreditation level in the region.</p>
<p>The University currently serves about&nbsp;16,000 students&nbsp;who are pursuing pre bachelor, bachelor, specialist and master degrees in&nbsp;46 majors&nbsp;and&nbsp;22 fields of knowledge. About&nbsp;1300&nbsp;students represent almost&nbsp;50&nbsp;countries worldwide.</p>
<p>SSU is included in the directory of world’s best universities by the&nbsp;Times Higher Education World University Rankings. Sumy State University enters the TOP-group (3%) of leading universities of the world and is classified as a university with high research intensity according to the international ranking of higher education institutions&nbsp;QS World University Rankings.&nbsp;SSU is in the TOP-100 according to&nbsp;QS University Rankings: EECA&nbsp;(Emerging Europe and Central Asia) among the universities of this region. According to these rankings, SSU enters the TOP-5 Ukrainian universities. SSU also ranked 101-150 among the fastest-rising young stars of the higher education world by the QS.</p>
<p>Sumy State University is the first Ukrainian higher education institution, which passed in 2014 an independent&nbsp;external audit of the QS Company&nbsp;and was given&nbsp;the highest points (5 stars)&nbsp;in such categories as Teaching, Engagement, Access and E-learning.</p>
<p>The University holds the highest position among Ukrainian higher education institutions for the number of prize-winning places in&nbsp;All-Ukrainian competitions of students’ research works&nbsp;and is among leaders in&nbsp;All-Ukrainian Olympiads in educational disciplines, training areas and majors.<strong>&nbsp;</strong></p>
<h5 style="text-align: left;"><span style="color: #800000;"><strong>INTERNATIONAL ACTIVITY</strong></span></h5>
<p>Sumy State University cooperates with more than&nbsp;<strong>200 partners</strong>&nbsp;from the USA, Great Britain, Germany, Austria, France, Belgium, Sweden, Poland, Lithuania, Bulgaria, the Czech Republic, Slovakia, Romania, Japan, South Korea, China and other countries of the world.</p>
<p>SSU is a reliable partner for joint projects in frames of international grant programs of EU<strong>&nbsp;(Tempus, Erasmus Mundus, Jean Monnet, Erasmus+, Horizon 2020)</strong>, United Nation Development Program, British Council, the World Bank, bilateral scientific and research projects, grants of private foundations. The University accomplishes more than 200 grants annually. For the last 5 years the amount of research work in frames of international grant projects has increased in 20 times.</p>
<p>The University actively develops academic mobility programs, including long-term and short-term studying, internships and placement programs for undergraduate and postgraduate students, research and teaching staff, as well as administrative staff using technologies of credit transfer and recognition of academic results.<strong>&nbsp;</strong></p>
<h5><span style="color: #800000;"><strong>RESEARCH ACTIVITY</strong></span></h5>
<p>According to&nbsp;<strong>SCOPUS database</strong>, Sumy State University holds a leading position among Ukrainian higher education and research institutions for h-index (the index of research impact) and the number of citations by international academic community.</p>
<p>Corresponding Members of the National Academy of Science of Ukraine, 120 Doctors of Sciences, Professors and 650 Candidates of Sciences (PhD), Associate Professors represent academic staff of the University. There are postgraduate and post-doctoral programs in 21 majors, degree awarding academic councils.</p>
<p>According to the number of commercial contracts and grants, and the efficiency of use of budget funds, Sumy State University is one of the leaders among Ukrainian universities.</p>
<h4 style="text-align: center;"><span style="color: #333399;"><strong>Medical Institute</strong></span></h4>
<p>Sumy Medical Institute&nbsp;was founded in 1992 as the Medical Faculty of Sumy State University.</p>
<p>Medical Institute provides training on such specialties as “General Medicine” and “Dentistry”. Postgraduate education is provided on such specialties as “Therapy”, “Surgery”, “General practice”, “Family Medicine”, “Obstetrics and Gynecology”, “Infectious Disease,” and “Pediatrics.”</p>
<p>Students and the academic staff have an opportunity to enter Ph.D. programs of 9 specialties. Nowadays, 50 graduate students and 3 doctoral students are studying for receiving an academic degree. Currently work is done by one research grant of the President of Ukraine.</p>
<p>Since 1992, the preparation of international students for today contingent of foreign nationals numbering about 800 people from 56 countries began. In autumn 2005 Medical Institute of Sumy State University was founded, which consisted of such 2 departments as Medical Education and Postgraduate Medical Education.</p>
<p>In Medical Institute provide all conditions for getting and mastering knowledge of the latest medical science, methods of diagnosis and treatment. The students have got the possibility to practice in the Museum of Normal and Pathological Anatomy, as well as attend computer labs, library, dining room, gym, stadium, swimming pool and dormitories.</p>
<h5><span style="color: #800000;"><strong>DEPARTMENTS OF SSU MEDICAL INSTITUTE:</strong></span></h5>
<p>•&nbsp;Department of Human Anatomy;<br>
    •&nbsp;Department of Biophysics, Biochemistry, Pharmacology and Biomolecular Engineering&nbsp;;<br>
    •&nbsp;Department of Hygiene and Ecology of Microbiology, Virology and Immunology;<br>
    •&nbsp;Department of Infection Disease with Epidemiology&nbsp;;<br>
    •&nbsp;Department of Orthopedics, Traumatology and Emergency Conditions;<br>
    •&nbsp;Department of Pathomorphology;<br>
    •&nbsp;Department of Obstetrics and Gynecology;<br>
    •&nbsp;Department of Physiology and Pathophysiology;&nbsp;<br>
    •&nbsp;Department of General Surgery, Radiation Medicine, and Phtisiology;<br>
    •&nbsp;Department of Neurosurgery and Neurology;<br>
    •&nbsp;Department of Pediatrics with Medical Genetic;<br>
    •&nbsp;Department of Surgery with Children Surgery and Urology.</p>
    <p>Theoretical departments of the Institute are located in a separate building, which consist of the following research <strong>laboratories</strong>:</p>
    <ol>
        <li>Center for morphological Research (light and electron microscopy, atomic absorption spectrophotometry, Laboratory of Biomechanics);<br>
            2. Chemistry and Toxicology Laboratory;<br>
            3. Microbiology Laboratory;<br>
            4. Biochemistry Laboratory;<br>
            5. Research Center of Molecular Genetic Research;<br>
            6. Laboratory of biomaterials.<strong>&nbsp;</strong></li>
        </ol>
        <h5><span style="color: #800000;"><strong>THEORETICAL RESEARCH DEPARTMENTS INVOLVE THE FOLLOWING AREAS:</strong></span></h5>
        <ol>
            <li>Medical and biological aspects of water and salt and electrolyte metabolism of the body in health and disease;<br>
                2. The role of the allelic polymorphism in the development of pathological processes and diseases;<br>
                3. Creating biocompatible nanocomposite materials for orthopedic and surgery.</li>
            </ol>
            <p>The educational process at the University is provided in Ukrainian, Russian and English languages. Studying in English was applied in 2004 for students of the Medical Institute and it was the first at the University. Since 2006 Medical Institute turned to educational process organization according to the credit-module system with appraisal plan ESTC (European Credit Transfer System), which means one of the main stages of integration into European educational process, which allow graduates of higher education institutions to be competitive at the labour-market. In 2012, the list of specialties for the major “Medical and Preventive Care” has been expanded. In 27 December 2012, according to the resolution of the State Accreditation Committee of Ukraine, SSU Medical Institute received the right to train specialists in the major “Dentistry.” In 20 years the medical research institution appeared where the Institute received its achievements and investigations. During this time, the institution prepared nearly 2,000 Doctors, 1,500 of them work in hospitals of Sumy Oblast and other. Clinical departments are located mostly at Sumy hospitals, which are fitted out with modern diagnostic equipment. SSU Medical Institute students can also participate in multi-center international studies.<strong>&nbsp;</strong></p>
            <h5><span style="color: #800000;"><strong>THE MAIN DIRECTIONS OF CLINICAL RESEARCH:</strong></span></h5>
            <ol>
                <li>Cardiology, Rheumatology;<br>
                    2. Problems of Diagnosis and Treatment of Infectious Diseases and HIV/AIDS;<br>
                    3. Pediatrics;<br>
                    4. Surgery and Oncology;<br>
                    5. Neurosurgery;<br>
                    6. Gynecology;<br>
                    7. Orthopedics.<strong>&nbsp;</strong></li>
                </ol>
                <h5><span style="color: #800000;"><strong>MEDICAL INSTITUTE CARRIES OUT RESEARCH IN THE FOLLOWING AREAS:</strong></span></h5>
                <ol>
                    <li>Medical and biological aspects of water and salt and electrolyte metabolism of the body in health and disease;<br>
                        2. The role of the allelic polymorphism in the development of pathological processes and disease;<br>
                        3. Creating a biocompatible nanocomposite materials;<br>
                        4. Мicroelementhoses study.<strong>&nbsp;</strong></li>
                    </ol>
                    <h5><span style="color: #800000;"><strong>MEDICAL INSTITUTE HAS THE FOLLOWING LABORATORIES:</strong></span></h5>
                    <ol>
                        <li>Scientific Laboratory of Molecular Genetic Studies;<br>
                            2. Pathology Research Center;<br>
                            3. Center for Morphological Studies;<br>
                            4. Regional Centre for Environmental, Сhemical and Toxicological Monitoring and Biomedical Research;<br>
                            5. Laboratory of Biomaterials.<strong>&nbsp;</strong></li>
                        </ol>
                        <h5><span style="color: #800000;"><strong>Education and Qualification Degrees of SSU Medical Institute</strong></span></h5>
                        <p>Sumy Medical Institute is attested according to the top educational level of accreditation. Among 200 teachers there are 25 Doctors of Sciences, 150 Candidates of Sciences, including Honored educational workers of Ukraine, laureates of State Prize of Ukraine perform educational, scientific, as well as clinical and upbringing work at 17 medical departments and 7 general departments of Sumy State University.</p>
                        <p>Medical Institute provides the high quality education to foreign students, who are looking for a quality education at an affordable course fees. Medical Institute prepares specialists according to the following education and qualification degrees as specialists for the following specialties: “General medicine,” “Preventive medicine” and “Dentistry,” as well as different postgraduate educational specialties.</p>
                        <h5><span style="color: #800000;"><strong>General Medicine</strong></span></h5>
                        <p>During the six years of study undergraduate educational programme, students study different fundamental and clinical disciplines. Studying encompasses a variety of health care practices evolved to maintain and restore health by the prevention and treatment of diseases. Modern medicine applies the health science, biomedical and genetic research and medical technology to diagnose and treat disease, through medication, surgery, or some other forms of treatment. Medical Institute is widely known for its multiform innovative teaching, practical training and research programs of international cooperation.</p>
                        <p>Students study in groups that consist of 8-10 students due to selected language. The second year students attend their clinical studies, where they can gain an experience in caring for the patients. At the beginning of the third year of study clinical disciplines are observed. Students can study any topic they are interested in and to improve their knowledge in the departments of students research communities. The program must be passed successfully before students are permitted to graduate. Student life includes: academic mobility programs, international conferences, summer international practice, operate student initiative, sports, health and lifestyle volunteering.</p>
                        <h5><span style="color: #800000;"><strong>Preventive Medicine</strong></span></h5>
                        <p>From 2012, Medical Institute prepares specialists in the sphere of medical prophylaxis (“Preventive Medicine”). There are modern sanitary-hygienic laboratories, where students can practice their skills are created to improve educational process. Among the new opportunities for graduates are the status of a civil servant, work in expert laboratories, inspection bodies. After the studying at the specialty “Preventive Medicine” a possibility to be the physician in the spheres of virologist, genetics, hygienists, nutritionists, epidemiologists, immunologists, a specialist in the organization and management of health care and others is provided.</p>
                        <h5><span style="color: #800000;"><strong>Dentistry</strong></span></h5>
                        <p>Dentistry is the branch of medicine that is involved in the study, diagnosis, prevention, and treatment of diseases, disorders and conditions of the oral cavity, the maxillofacial area and the adjacent and associated structures, and their impact on the human body. To the layman, dentistry tends to be perceived as being focused primarily on human teeth, though it is not limited strictly to this. Dentistry is widely considered necessary for complete overall health.</p>
                        <p>The course of “Dentistry” in Medical Institute aims at preparing students for the industry by equipping them with all the necessary theoretical and clinical knowledge, practical skills. The students train the basic subjects of medical and biological disciplines, as well as various clinical subjects, which are so important for future work.</p>
                        <p>The structure of the newly formed entity of Sumy Medical Institute includes classrooms, students’ ambulatory, modern dental clinic, as well as computer and phantom classes, equipped with the modern scientific and technical requirements.</p>
                        <h5><span style="color: #800000;"><strong>Clinical Practices</strong></span></h5>
                        <p>All clinical departments are located in the leading institutions of the regional center. They took the status of clinical department according to order of the Ministry of Health and the order of the Regional Administration. The status of clinical has: regional hospital for adults, hospital for children, Infection hospital, Clinic of Radiation protection, Hospital for Invalids of Great patriotic war, Center for Obstetrics, Gynecology and Reproduction, Oncology Center, Antiphthisic dispensary, venereology dispensary, neuropsychiatric dispensary, medical and sports clinic, City hospital № 1, № 4, № 5, Clinical Hospital for children. The total number of bedspaces is about 4,000 beds.</p>
                        <p>Clinical facilities are equipped with such modern equipment as CT, stationary pressure chamber, biochemistry analyzer, apparatus for extracorporeal detoxification, mechanical ventilation of lungs, cardiomonitors, radiological and endoscopic equipment, Ultrasonic diagnosis apparatus, vehicle of artificial kidney and other. The teaching staff of the Institute uses the latest ultrasonic diagnostic apparatus, encephalograph, Doppler, biochemical, clinical and ELISA cardiotocograph analyzers and many other devices.</p>
                        <p>Collectives of the clinical developed and enforced a number of regional programmes. The aim of these is to improve the diagnosis, treatment, to prevent the disease and to reduce their harm. Among the regional programs are: “Antihepatitis,” which help to make better the diagnosis and treatment of acute and chronic hepatitis of viral etiology. “Prevention of Cerebrovascular diseases,” according to the etiology and risk factors is studying, measures for prevention of stroke and rehabilitation patients are developing. Teachers take part in the implementation of state and regional programs, such as “Health,” “Children of Ukraine,” “Oncology,” “Diabetes,” “The Programme of Prevention and Treatment of Hypertension in Ukraine,” etc.</p>
                        <p>At the clinic or work plans to open regional diagnostic and treatment centers: hematological (clinical infectious diseases), pancreohepatobiliar (clinical surgery), cerebrovascular disease (Neurology Clinic), gastrointestinal bleeding and diabetic foot (surgery and hospital care), psychosomatic disorders (Clinic of Psychiatry) and others.</p>
                        <p>Professors and associate professors conduct the clinical rounds of patients, counseling techniques in clinics and review of patients in hospitals almost all hospitals of Sumy. Assistant and clinical residents are treating patients of departments and make night duty.</p>
                        <p>Surgeons performed complex and sometimes unique surgery in surgical and oncological diseases. In Sumy for the first time region were put into practice such complex surgeries as: disemboweling of pelvic, pancreas-duodenal resection for cancer of the pancreas, lymph drainage of the thoracic duct and umbilical vein for chemotherapy, removing tumors of the anterior abdominal wall defect with plastic skin-muscle on the vascular pedicle flap, resection of the lower lip with resection of the mandible and skin-grafting of the defect in the muscle flap vascular pedicle, shoulder-blade amputation, removal of tumors of the mediastinum sternal access lung removal and hemipericardium removal, parasternal limfadenektomia about breast cancer, removal extra-abdominal desmoids of the neck, flap and the plastic arts of autodermal layer and alloplasty nylon wall on the complex recurrent post-operative ventral hernias, organkeeping surgery for splenic injuries, right-side and left-side hemihepatektomia, in intestinal-mesentery applique for acute and chronic adhesive disease with syndrome of acute intestinal obstruction.</p>
                        <p>The use of sodium hypochlorite solution of various concentrations in patients with purulent infection was introduced in the clinic. Reasonable medical and diagnostic tactics in patients with perforated gastro-duodenal ulcer. For the first time in the region at the Otolaryngology Clinic introduced endoscopic methods of diagnosis and manipulation of diseases of the nose and paranasal sinuses. Methodologies of treatment of patients are improved on the disease of thyroid depending on immune status and other. The level of emergency and urgent care to patients of Sumy oblast significantly increased which involve of professors and associate professors become better. The question of visits the patient by doctors and consultants staff departments of the Medical institute is under constant control of the management of health care.</p>
                        <p>Every year over 100 new methodologies are inculcated in medical diagnostic process and help to improve the effective of treatment and diagnostics. The great deal of work is making: visits to regional health care facilities, review of medical records, working in consulting and appraisal committees, conferences, taking part in the work of college of Health Department, and etc. Such work of scientific and medical societies becomes more effective and interesting: infectious disease specialists, pediatricians, surgeons, internists, neurologists, obstetricians, where the heads are teachers of the institute. More often regional research and practice conferences began to be conducted with edition of theses. Reading of lectures is entered by the students of senior courses for students and students of middle educational establishments.</p>
                        <p>The faculty of Clinical departments executes a large amount of health care during the summer practical training. Each year over 20 teachers involved in this work. Sumy clinical hospitals are the base summer practical training. The highly skilled specialists are managers of these bases. The programs of practices for students of all courses in all disciplines, uniform diary of practices, and continuous application of practical skills are developed. The students show during the practice the reveal qualitative theory, deontological knowledge, skills for their practical implementation.</p>
                        <p>Making a great part of health care and treatment work, faculty Medical Institute does not stop there, not complacency, but rather trying to find new forms to improve efficiency of treatment, diagnosis and prevention.</p>
                        <h5><span style="color: #800000;"><strong>POSTGRADUATE EDUCATION IN SSU MEDICAL INSTITUTE</strong></span></h5>
                        <p>The main purpose of Medical Postgraduate Education Faculty is delivering the requirements of the regional health care institutions, improving professionals skilled in various specialties based on the formation of continuous postgraduate education, continuous improvement of qualification of doctors, which is based on a system of State standards. Training of health professionals at postgraduate stage began in Sumy Medical Institute in September 2003. Graduates of medical schools Ukraine, received his medical degree, started training in the following specialties: obstetrics and gynecology, internal medicine, general practice, family medicine, infectious diseases, pediatrics, radiology and surgery. Study on full-time cycles provides by departments of Medical Institute, distance education is made on the bases of approved regional, district and city hospitals.</p>
                        <h5><strong><span style="color: #800000;">DEPARTMENTS OF POSTGRADUATE EDUCATION:</span></strong></h5>
                        <h5>• Internal Medicine of Postgraduate Education;<br>
                            • Family Medicine and Propaedeutic to Internal Medicine;<br>
                            • Pediatrics of Postgraduate Education;<br>
                            • Social Medicine, Organization and Economics of Health Protection.</h5>
                            <p>Along with the introduction of internship Medical Institute of Sumy State University was entitled to train masters of these disciplines. Masters held during their internship full-cycle, extended for 3 months by reducing the distance cycle. Introduction to the Master’s happening on a competition for specialty internship. Clinical residencies is a contract following specialties: obstetrics and gynecology, anesthesiology, internal medicine, dermatovenereology, general practice, family medicine, infectious diseases, neurology, pediatrics, psychiatry, orthopedics and traumatology, oncology, ophthalmology, pathological anatomy, phthisiology, surgery.</p>
                            <p>The faculty established the publication of guidelines, manuals, newsletters for medical students, interns and masters. To all doctors, who need accommodation in the lodging during their training, places in the dormitories are completely provided. Since 2009, the training of medical specialists in courses of thematic improvement in regional science-training Center of Endoscopic Diagnostic and Minimally Invasive Surgery began.</p>
                            <h5><span style="color: #800000;"><strong>MEDICAL INSTITUTE PROVIDES</strong></span></h5>
                            <p>• Close cooperation with leading medical educational institutions and hospitals of Ukraine (P.L. Shupik National Medical Academy of Postgraduate Education, Institute of Children and Adolescents Health Care of the Academy of Medical Sciences of Ukraine, etc.);<br>
                                • Immutably high level of knowledge of students and interns (according to State licensed qualifying test “Step-3”);<br>
                                • First working place for graduates is ensured;<br>
                                • Schooling professionals at Master academic programmes, clinical studies and postgraduate courses.</p>
                                <h5><span style="color: #800000;"><strong>DORMITORIES OF SSU MEDICAL INSTITUTE</strong></span></h5>
                                <p>Sumy State University Students’ City consists of 5 dormitories, where more than 800 students are living. All students, who want to live in a dormitory, as well as student families, are ensured with dormitories. The University Residence provided an excellent service, which has met the living needs of thousands of long term and short term stay clients. This facility built an enviable reputation for its services and is recognized for its exceptional value-for-money. Recently the University has opened a dormitory, which provides excellent residential facilities. Each room in the dormitory is provided with kitchen, where students can cook everything they want. Students need to supply their own kitchen utensils. Foodstuff may be bought in various food shops. All the kitchens are provided with heaters. Our dormitories feature 24-hour access to security and emergency services, simplifying their needs. The University Residence provides students with modern, fully serviced and comfortable accommodation. Continuous investment is made to ensure that the facilities serve the student within the context of a modern academic residence.</p>
                                <h4 style="text-align: center;"><span style="color: #333399;"><strong>Academic and Research Institute of Finance, Economics and Management</strong></span></h4>
                                <p>The faculty of Economics and Management&nbsp;of SSU is a leader of education in Economics, Management and Administration in the region. It has quarter-century experience. The fact about quality and traditions of economic education shows that the faculty is one of the oldest economic schools in Sumy region, as well as a provider of personnel for enterprises, establishments and educational institutions.</p>
                                <p>The faculty of Economics and Management appeared in May 1991. That year 50 students entered such specialty as “Economics of Enterprise,” as well as 25 students entered “Management of Organizations.” The number of students increased next year, so such three departments were organized: the department of Economics, the department of Finances, and the department of Management.</p>
                                <p>A distinctive feature of the faculty of Economics and Management is a wide choice of economic disciplines at the elder courses in region. Bachelor students have a unique opportunity to continue their study at the 4 main and other economic specialties such as: Administrative Management, Exchange Activity, Economics of Environment and Natural Resources, Project Management, as well as Business-Administration, and Government Service.</p>
                                <p>The faculty’s mission is to prepare a highly qualified, responsible, competent, competitive specialist at the labour market, whose activity will be connected with Economics, Management and Administration. Such students will master their profession; will be able to work effective according to the world standards with the high level of social and professional mobility.</p>
                                <p>For the present moment the faculty is headed by its graduate Dr. of Economics, Professor Olha V. Prokopenko. In general, there are 20 Professors and Dr. of Economics among teachers of the faculty.</p>
                                <p><strong>Faculty of Economics and Management consists of 5 departments:</strong></p>
                                <ul>
                                    <li><strong>Economics and Business-Administration;</strong></li>
                                    <li><strong>Economics Theory;</strong></li>
                                    <li><strong>Marketing and Innovative Activity;</strong></li>
                                    <li><strong>Management;</strong></li>
                                    <li><strong>Finances and Credit.</strong>&nbsp;</li>
                                </ul>
                                <p>The teaching staff of the faculty has more than 100 lecturers with academic degrees. The faculty provides a special opportunity for its students to learn their disciplines with the international teachers.</p>
                                <p>The faculty’s scientific interests comprise problems of the environmental economics and loss indemnity, which are connected with environmental pollution; theories of the investment and innovative processes management mechanisms; methodologies and methodic to evaluate enterprise economic potential; formation of the territories social and economic development strategies; social and economic problems of the informational society, etc.</p>
                                <p><strong>Such main modern scientific schools are developed at the faculty are:</strong></p>
                                <p>1.&nbsp;“Economics of the systems development and sustainable informational society”;<br>
                                    2.&nbsp;“Management of the enterprise innovative development, marketing and management of innovations”;<br>
                                    3.&nbsp;“Ecological and economic problems of heat and power engineering, management of free air emission at the interstate level”.</p>
                                    <p>Scientific schools of the faculty trained 12 Doctors and over 100 PhDs in Economics. More than thousand scientific publications, including ten monographs and manuals were issued.</p>
                                    <p>During the last years, the teachers of the faculty investigated and issued a lot of manuals and educational books in Economics of Enterprise, Marketing, Management, Economic of Sustainable Development, Personnel Management, Management NDO, problems of environmental protection, investment and innovative activity, etc.</p>
                                    <p>Students from the faculty of Economics and Management have their traditional training at summer scientific schools not only in Ukraine, but also in the USA and the European countries. Since 2014, the first year of study students have got the possibility to get the European diploma at the same time with their education at SSU with the help of “double diploma” program, using technologies of credit transfer and recognition of academic results.</p>
                                    <h4 style="text-align: center;"><span style="color: #333399;"><strong>Academic and Research Institute of Law</strong></span></h4>
                                    <p>Academic and Research Institute of Law was established in May 2016.</p>
                                    <p>During the period from 2006 till present, Academic and Research Institute of Law was has trained more than 1253 specialists in Law.</p>
                                    <p><strong>The purposes of the Institute’s Foundation</strong>&nbsp;consist in meeting the growing demand for highly trained specialists in the field of Law that have solid theoretical knowledge and practical skills of their application, revival, preservation and promotion of Ukrainian legal affairs and traditions, the implementation of cultural and educational activities, fundamental and applied research, promotion of Ukrainian law-making and enforcement process.</p>
                                    <p><strong>The objectives of the Institute</strong>&nbsp;are training qualified professionals in the field of Law, familiarizing students with general and legal culture, formation of high moral qualities, patriotism, respect for law, social responsibility, teamwork in accordance with the actual situations and the norms of law, creating appropriate conditions for the harmonious development of the personality.</p>
                                    <p><strong>Academic Staff of the Academic and Research Institute of Law</strong>&nbsp;includes 11 Doctors of Science and 35 Candidates of Science (Ph.D.). Most lecturers have extensive practical experience in the legal field.</p>
                                    <p><strong>Structure of the Academic and Research Institute of Law</strong></p>
                                    <ul>
                                        <li>The Department of Administrative, Economic Law and Financial and Economic Security</li>
                                        <li>The Department of Criminal Law and Procedure</li>
                                        <li>The Department of Constitutional Law, Theory and History of State and Law</li>
                                        <li>The Department of International, European and Environmental Law</li>
                                        <li>The Department of Civil–Legal Disciplines and Financial Law</li>
                                    </ul>
                                    <p><strong>Legal Clinic of Sumy State University</strong></p>
                                    <p>The Legal Clinic of SSU operates at the Academic and Research Institute of Law, where students of the Institute provide free legal aid for the society. The work of SSU Legal Clinic is aimed at providing practical training for the students’ professional skills, their awareness of the mission of legal profession and broadening an access for the society to legal aid.</p>
                                    <p><strong>SSU Academic and Research Institute of Law provides training for lawyers in the following majors:</strong></p>
                                    <p><strong><em>Jurisprudence</em></strong></p>
                                    <p><em>Qualification degrees:</em></p>
                                    <ul>
                                        <li>Bachelor</li>
                                        <li>Specialist</li>
                                        <li>Master</li>
                                    </ul>
                                    <p><strong><em>Financial and Economic Security Management (FESM)</em></strong></p>
                                    <p><em>Qualification degree:</em></p>
                                    <ul>
                                        <li>Master</li>
                                    </ul>
                                    <p><strong>Modes of study:</strong>&nbsp;full-time, part-time, distance learning.</p>
                                    <p>The postgraduate and postdoctoral programmes are provided for the specialty 12.00.07 of the Department of Administrative, Economic Law and Financial and Economic Security.</p>
                                    <p>For each degree and major there are places of state order.</p>
                                    <p>The cooperation with international partners in the sphere of education is one of the priorities of international activity at SSU Academic and Research Institute of Law. The Departments of the Institute maintain business relations with international colleagues.&nbsp;</p>
                                    <h5><span style="color: #800000;"><strong>LIBRARY</strong></span></h5>
                                    <p>Library as the cultural center of the medical institute is an important structural unit, which provides the educational, scientific and research processes. An important role of providing students and University staff with the materials belongs to the library. The scientific and research library of the Medical Institute is an auxiliary for teaching, scientific and research, informational and cultural enlightening division.T he work of library is purposed for building and protecting of book stocks and meeting the readers’ needs and the tasks of teaching and research processes with most possible effectiveness. One of the main tasks of the library is supporting the teaching process and the independent work of the students, which requires an effective interaction with the Teaching division, dean’s offices and departments. The stock formation sector and the textbook loan system keep the catalogue reflecting the extent to which the teaching process is provided with books. There are a lot of reading halls, connected with the University data bank information and the Internet. The references and information facilities are open to the society.</p>
                                    <h5><span style="color: #800000;"><strong>CAREER OPPORTUNITIES</strong></span></h5>
                                    <p>Medicine offers a career that allows making choice over 50 specialties and subspecialties. Everybody needs to start career planning in order to be able to choose a suitable specialty. Career planning should be regarded as an integral part of the personal development. So start your career planning and become qualified in the specialty you prefer most of all!</p>
                                    <p>SSU Medical Institute as the one of premiere academic medical centers in Ukraine offers exceptional employment opportunities for students in a variety of specialties. Medical Institute provides training on such specialties as “General Medicine,” “Prophylactic Medicine” and “Stomatology.” Postgraduate internship is provided on such specialties as “Therapy,” “Surgery,” “General practice,” “Family Medicine,” “Obstetrics and Gynecology,” “Infectious Disease,” “Pediatrics,” according to specialization. Students and academic staff have an opportunity to enter Ph.D. programs of 9 specialties. At present time, 50 graduate students and 5 doctoral students are studying to receive the education degree.</p>
                                    <h5><span style="color: #800000;"><strong>EXTRACURRICULAR ACTIVITIES</strong></span></h5>
                                    <p>36 kinds of sports and about 100 sports groups&nbsp;are available at the University. Sports teams perform at the premier league level. About 100 students are the record breakers and prize winners of the Olympic Games, World, European and Ukrainian Championships.</p>
                                    <p>Three SSU undergraduates and masters were invited to join Ukrainian national team for the&nbsp;XXX Summer Olympic Games&nbsp;in London; and&nbsp;six SSU undergraduates and masters&nbsp;participated in the&nbsp;XXII Winter Olympic Games&nbsp;in Sochi. They were awarded with gold medals in relay biathlon race and bronze medals in boxing and biathlon sprint.</p>
                                    
    </div>
</div>

<?php include $path.'/layouts/sidebar.php' ?>
<?php include $path.'/layouts/footer.php' ?>