
<?php 
    $path = $_SERVER['DOCUMENT_ROOT'];
    include $path.'/layouts/header.php'  ;
    title_page('Université d’Etat Adyguée, ville Maïkop')
?>


<?php include $path.'/layouts/feature.php';
    feature_txt('Université d’Etat Adyguée, ville Maïkop', "russia");
?>

<div class="post">
    <div class="post-header"><div class="col-sm-12 col-md-12">
        <h2 class="">Université d’Etat Adyguée, ville Maïkop</h2>
    </div></div>
    <div class="post-img"><img src="/images/universities/russia/41.jpg" alt=""></div>
    <div class="post-txt">
    <p></p><p style="text-align: justify;">Adyghe State University is a leading educational and research center of the Republic of Adygea. ASU history dates back to 1940, when the city of Maikop, opened Teachers’ Institute, which became in 1952 Adyghe Pedagogical Institute, and in 1993 – State University. The opening of the university marked the beginning of higher education in Adygea, created the necessary conditions for the emergence of other educational and research institutions in the region.</p>
<p style="text-align: justify;">Today it is one of the leading universities in the South of Russia, which has well-known scientific schools, highly qualified teaching staff, modern technology and information base. As a recognized educational, scientific and cultural center of the region, ASU continues to develop dynamically and actively participates in the formation of a competitive “knowledge economy”.</p>
<p style="text-align: justify;">In October 2015 ASU noted the important date – the 75th anniversary of its founding. ASU went a long way, rich in significant dates and events, and the 75-year anniversary was the occasion for many generations of teachers, staff and students. Over the years, the walls of the university left tens of thousands of professionals, including prominent scientists, teachers, writers, public figures. The university has become a real source of skilled workers for domestic and economic complex of the Republic of Adygea and other territories in southern Russia. Its graduates make up a scientific, educational, political, economic and cultural elite of the region.</p>
<p style="text-align: justify;">Anyone who is motivated to increase their knowledge and professional competence, ASU provides the opportunity to study in different educational paths and levels – from preparing to enter the university to obtain academic degrees and academic titles.</p>
<p style="text-align: justify;">Profound professional knowledge and practical experience of university teachers and employees, respect for the classical traditions of the institution, the modern scientific and technical base and one of the best research libraries of Southern Russia provide a high level of training and allow the university to make a worthy contribution to the development of Adygea.</p>
<p style="text-align: justify;">Rector of the Adygeya State University, is a Doctor of Social Sciences, Professor Rashid Dumalichevich Hunagov. Achievements and successes RD Hunagova in scientific and pedagogical activity marked by a number of awards and honors. R. Hunagov – member of the Academy of Pedagogical Sciences, the Academy of Social Sciences, Honored Worker of Kuban science, Honored Worker of Higher Professional Education of Russia, Honorary Doctor of the Institute of Sociology of the Abkhazian State University, Southern Federal University, the Mongolian State University, an honorary member of the Academic Oksforskogo Union Club Rectors of Europe. Elected academician – a foreign member of the Serbian Academy of Education (Serbia, Belgrade), has the honorary title of “Excellence in Education of Mongolia.” sign “Rector of the Year” was awarded repeatedly.</p>
<p style="text-align: justify;">He was awarded medals “Glory of Adygea”, “For outstanding contribution to the development of Kuban”, the Honorary silver medal. IN AND. Vernadsky, the Jubilee Medal “100 years of Russian trade unions”, “Professional Leader” Center Medal of biographical studies of Cambridge, a silver medal. Sorokin “For contribution to the development of the sociology of” Medal of the State Council-Hase of the Republic of Adygea “Law. Debt. Honor “Honorary Diploma of the Council of Federation of the Federal Assembly of the Russian Federation, the Honorary Diploma of the Legislative Assembly of Krasnodar Region. Cavalier of the Order of “Sophia”, the winner of the European Socrates Prize Winner of the American “Golden Certificate of Quality” award and the medal “For contribution to the development of science and culture”, the winner of the contest of scientific works on Caucasian Southern Russia them. YA Zhdanov.</p>
<p style="text-align: justify;">Since its founding to the present day high school successfully fulfills three main functions of modern classical university – education, science, participation in ensuring the region’s development. ASU objectives are: to preserve and increase the intellectual potential, the formation of innovative culture, the promotion of high technologies in the economy and social sphere of the Republic of Adygea, a humanistic education system of values, the development of culture and the creative traditions of the society, the preservation and development of the Circassian language and culture.</p>
<p style="text-align: justify;">The university enrolled more than 11 thousand students from Adygeya, other regions of Russia and foreign countries on a wide range of vocational training programs. The ASU licenses more than 100 areas of training in higher (undergraduate, graduate, specialty), secondary vocational and further education. Teaching and research university structure includes: 2 Institute (Institute of Arts, the Institute of Physical Culture and Judo), 12 faculties (Mathematics and Computer Science, Engineering Physics, natural science, history, philology, Adygea philology and culture, foreign languages, law, economics, Teachers, faculty of social technologies and tourism, international), humanitarian and technical College, research Institute of complex problems, research centers, laboratories, museums, National space Centre services, student business incubator, vocational training center. It operates a branch in Belorechensk Krasnodar Territory. At ASU successfully it works Republican natural-mathematical school. The University has developed social infrastructure, sanatorium, the Palace of Sports, holiday villages and other units of cultural and recreational orientation.</p>
<p style="text-align: justify;">For many decades, the university has formed a powerful scientific and pedagogical potential, it employs more than 700 faculty and staff, about 100 doctors and 370 candidates of sciences, 54 honored workers of science and arts of Russia and Adygea, 24 academicians of the Russian and international academies, 69 honored workers of education , culture and sports in Russia and Adygea.</p>
<p style="text-align: justify;">The development strategy of the ASP based on the establishment of a multilevel and multifunctional research complex, capable of ensuring the continuity of pre-university education and primary vocational to postgraduate and further for different categories of students.</p>
<p style="text-align: justify;">The quality of preparation of graduates of ASU has been recognized at national and international levels. University introduced in the Federal Register “All-Russian Book of Honor” (2008), “Russian Board of Honor” (2012). Educational programs of the university have been certified by the Chamber of Commerce of the Russian Federation, the European Scientific and Industrial Chamber (Belgium), the Association of Lawyers of Russia, the European Organization for Quality (EOQ). ASU is the winner of numerous competitions, including: “One hundred best goods of Russia”, “The best training centers of the Russian Federation” (2011), “100 best universities in Russia”, “Best Regional High School” (2012), “Best company of the year “(2013) etc. educational programs of the University for a number of years. (2012 -. 2015) are the winners of the All-Russian project” The best educational programs of innovative Russia “. In 2014, the results of the All-Russian competition of Ministry of Education of the Russian Federation on the quality of education ASU project “Proposals for quality assurance of students at the higher education level,” entered the top twenty and was the winner of the contest. The quality management system ASP, based on the requirements of ISO 9001 series of quality standards: 2008, successfully passed the procedure of surveillance and recertification EvroStandartSert system. In 2015, the ASU is turned on by the international rating agency ARES in the category of Russian universities, the relevant European quality standards.</p>
<p style="text-align: justify;">High quality training supported by the results of students’ participation in regional and All-Russian Olympiads and competitions over the last 5 years, medals and diplomas of Ministry of Education of the Russian Federation, diplomas and awards received in 1224 ASU student.</p>
<p style="text-align: justify;">Formation of image of the classical university is impossible without modern training and methodological support. New Research Library ASU area of over 3,000 sq.m. It has a large computer park, working in an automated library system. The electronic library funds there are tens of thousands of e-books. Appreciation Scientific Library gave ASU Vladimir Vladimirovich Putin during a teleconference with heads of Russian universities in April 2010.</p>
<p style="text-align: justify;">In terms of global information, the role of the university as a conductor of the most progressive achievements. The rapid development of computer technology has led to the expansion of the channel capacity of the Internet access of up to 54 Mbit / c. ASU Computer park includes more than 1,000 computers, 44 computer classes, united in a local network. In the educational process are widely used information technology, teachers will organize lectures and practical classes with the use of multimedia and the Internet. It implemented a broad introduction to the educational process of distance learning based on a modular object-oriented dynamic learning environment Moodle. Corporate computer network based on fiber-optic channels tied into a single information space of all remote units of the University, including dormitories. In the academic buildings and dormitories installed wireless access points to the Internet (Wi-Fi).</p>
<p style="text-align: justify;">A special role in the innovation economy development tasks given to high school science. For 75-year history of the university have developed and are actively working dozens of schools of thought, many of which are known not only in Russia but also abroad. The main tasks of ASU at the present stage are: the establishment of a modern scientific infrastructure and equipment base; increasing the productivity of scientific research; the development of innovation; academic mobility. The focus is on strengthening the human resources component, improving the structure of university research, extension activities Institute for Complex Problems and business incubator, the creation of small innovative enterprises and the development of basic research in the field of natural, philosophical, historical, sociological and political sciences.</p>
<p style="text-align: justify;">The university post-graduate courses and 23 doctorate on 3 specialties, 7 dissertation councils for doctoral and master’s theses.</p>
<p style="text-align: justify;">Successfully operating in 2009 created the Research Institute of complex problems, including 4 R &amp; D centers, 11 laboratories, 3 museums, botanical gardens and other structures.</p>
<p style="text-align: justify;">Since 2012, it operates student “business incubator” with a wide network of experimental, advisory, innovative structures, which allowed an effective center of small business development in the region. Student Business Incubator ASU entered in September 2015 in the All-Russian public organization “Association of student business incubator of young entrepreneurs and scientists of Russia.”</p>
<p style="text-align: justify;">In 2010 it created a small enterprise “Geo-Vertex”. The result of his activity was the implementation of 93 economic agreements with organizations for 2010-2015. in scientific and industrial environment of the region introduced 20 large-scale products in the field of geoinformation technologies. At the stage of formation are small innovative companies, organized with a view to the practical application of results of intellectual activity in the field of Nutrition and Psychology: “AnalitBioHimTeh” LLC, “Psi-Master.”</p>
<p style="text-align: justify;">Performs research in priority areas of science, technology and engineering, “Nanosystems”, “Information and telecommunication systems”, “Environmental Management”, “Life Science”, “Security and Countering Terrorism”.</p>
<p style="text-align: justify;">Space Services Center, based at ASU, is implementing projects included in the program of the Federal Space Agency and the Cluster of space technologies and communications development fund development and commercialization of new Center “Skolkovo” technologies. ASU scientists have developed a new structural model for prediction and modeling of natural and socio-economic processes on the basis of the results of space activities.The GIS center ASU developed and patented a method for predicting the date and the water level extremely high floods, offered a fundamentally new method for predicting severe weather events.</p>
<p style="text-align: justify;">Research on the stabilization of unstable control dynamical systems. Developed theoretical foundation and built physical models of processes and phenomena associated with the movement of charged particles and radiation in various electromagnetic fields.</p>
<p style="text-align: justify;">The results of research by definition immunogenetic, physiological and nutritional status of the population of the Republic of Adygea allowed to create information and methodological basis of the genetic assessment and psychosomatic health. University scientists developed effective ways biokonservatsii rare and protected species of the Republic of Adygea. According to the results of monitoring of the biological diversity of the Northwest Caucasus in 2013 it was published in 2 volumes of “The Red Book of the Republic of Adygea”, which includes recommendations for the conservation, restoration and sustainable use of biodiversity for ecosystem stability in the region. In order to implement the joint project “Endemic plants and animals of Adygea and Düzce” formed an initiative group of scientists of Institute for Complex Problems ASU and Düzce University (Turkey).</p>
<p style="text-align: justify;">Actively introduced the concept of the formation of an integrated socio-economic infrastructure of the macro – and micro-regions of Southern Russia through the creation of special economic zones and inter-regional innovation clusters, taking into account the actual use of the competitive advantages of the Republic of Adygea. The university has developed and implemented transport logistics during the competition, the Universiade and other large-scale events. This development has been successfully tested at the Sochi Olympics in 2014.</p>
<p style="text-align: justify;">Also, Adyghe State University scientists developed advanced methodical and methodological tools of modern research of ethno-social processes for the prevention and management of inter-ethnic tensions in the multiethnic region. In this area in 2015 the University won a grant for the project “Ethno-social processes and ethnic tensions in the South of Russia: the improvement of analytical tools and methods of regulation ‘(the total amount of funding – 16 million rubles..).</p>
<p style="text-align: justify;">Much attention is given to the problems of functioning and development of the Circassian language, literature and culture.</p>
<p style="text-align: justify;">The total amount of disbursements by NTP, grants (467 R &amp; D) over the past 5 years has exceeded 206 million. Rub., The amount of financing of international projects totaled around 57 mln. Rub.</p>
<p style="text-align: justify;">In recent years, sharply increased Publication teachers activity significantly increased the number of articles cited in indexed databases (RISC, Web of Science, Scopus), increased the number of certificates of registration of intellectual property and patents.</p>
<p style="text-align: justify;">Development of basic scientific fields is based on system integration with institutions of RAS, a wide range of Russian and foreign partners and potential users of the results of scientific research. One example of successful integration practices are basic departments and laboratories, which have a network structure and based on cooperation ASU and Southern Scientific Center RAS.</p>
<p style="text-align: justify;">Integration of the educational process with the science and production is carried out with the participation of undergraduate and graduate students. Each year, about 2,500 students are the performers of research, the results of studies published over 600 student research papers. Actively working Student Scientific Society. On the basis of ASU research schools are 53 student research team. During the 2010-2014. on the results of Russian competition for the best scientific work of students of the university student got 590 degrees.</p>
<p style="text-align: justify;">ASU publishes 12 scientific journals and collections of scientific works 9. Since 1998, the scientific magazine “Journal of the Adygeya State University”, included in the list of leading peer-reviewed scientific journals and publications recommended by HAC RF for publishing papers competitors of scientific degrees of doctors and candidates of sciences. The journal is included in Ulrich’s Periodicals Directory International database.</p>
<p style="text-align: justify;">ASU cooperates with universities in Russia, CIS and foreign countries, is a member of the International Association of Universities. Concluded and successfully implemented 19 international cooperation agreements. As part of the contracts are held scientific conferences, organized joint laboratories, scientific and pedagogical activity of teachers, training of students. Much attention is paid to the introduction and integration of academic mobility programs in the world scientific community. Over the last 5 years 143 teacher and 737 students of ASU traveled abroad with professional objectives. At the same time in the educational process in the faculties and institutes ASU took 26 teachers from the USA, Germany, France, Syria, Finland. To participate in internships and conferences University received more than 100 international graduate students and professors. The university trains young people from near and far abroad. CIS, Syria, Turkey, Jordan, China, Mongolia, Palestine, Israel, Montenegro, Nigeria, Congo and others to strengthen the positions of ASU in the international arena contributes to the university’s participation in international educational and scientific programs . A powerful incentive for effective transition to tier education, the development of innovative approaches was the participation of educators and psychologists ASU in a project of the European Union “Tempus 4: Educational toward undergraduate social work program” in 2009-2012. in partnership with a number of leading universities in Germany, England, France and Italy. ASU researchers are involved in the international project on creation of the European Union on Russia Center South. Russian university partners (SFU, ASU, Volgograd State University) became the University of Kingston (UK) and Mr. Linchopinga (Sweden).</p>
<p style="text-align: justify;">The University has 5 academic buildings and constantly increasing its educational and laboratory areas. In 2009, it completed construction of a new Science Library, capable of meeting the highest level of educational needs of the scientific community in the region. Significantly increased educational-laboratory base of ASU in 2012, when they were put into operation two new original architectural decision of the body that have become a real decoration of the urban landscape: the educational building area of 7.6 thousand square meters. and Business Incubator area of 3 thousand sq. m. m. The fitness center “Akuanda” with an indoor 25-meter pool on the program of the party “United Russia”, “500 pools.” Built in 2014, In 2015, it completed construction of a monumental sports complex comprising Sports Palace and 9-storey dormitory. It opened after the reconstruction of ASU comfortable hostel with a health center on the first floor. Another new hostel with 180 seats and a sports core with a football field was opened on the territory of Humanities and Technical College ASU.</p>
<p style="text-align: justify;">The university developed a strong tradition of spiritual, moral, aesthetic, civic and patriotic education of students and labor. The talents of students are disclosed in numerous creative teams Cultural Center ASU: studio theater, folk and pop dance, vocal and instrumental ensemble, etc. Folk Ensemble “Nart ASU” Adyghe dance twice won the International Festival “Almond blossom” in Italy, repeatedly became the winner of Mediterranean folklore festival in Turkey and on an ongoing basis participated in the cultural program of the Olympic Games in Sochi. Student musical theater “Art Riton”, annually presenting to the audience new musicals, earned a standing ovation in many cities of Russia and the triumph made abroad at the Youth International Festival of Ancient Drama in Siracusa (Italy) with the musical “The last gift of Prometheus” .</p>
<p style="text-align: justify;">High levels of socio-cultural work with students allowed to ASU for the third time to become the winner of the RF Ministry of Education of the competition program of the activities of student organizations and to obtain additional financing in the amount of 15 mln. Rub. in areas of “Student Government” “Volunteering and social projects”, “Patriotism and tolerance”, “Sport and healthy lifestyle,” “Science and Innovation” and others.</p>
<p style="text-align: justify;">The highlight of 2015 was held in Adygea on the basis of ASU International festival “Student spring in Caucasus”, which was attended by students from all over Russia. Particular attention in the framework of the festival was given to the 70th anniversary of the victory of the Soviet people in the Great Patriotic War. most clearly shown Contribution of the regions of the North Caucasus and Transcaucasia countries in the Great Victory told Exhibition Complex “Street Wins” deployed in the courtyard of ASU, and competition of patriotic “Soldier’s envelope” songs that the youth alive the memory of those who gave their lives for the motherland. The culmination of the festival was a symbolic action “Candle of Memory”. June 2 at 4:00 at the Eternal Flame at the military memorial in Maikop gathered participants of the International festival – representatives of 20 regions of Russia and abroad, as well as residents of the capital of Adygea, supported the youth initiative, and together lit more than three thousand candles lit up the sky in memory of the victory and its heroes.</p>
<p style="text-align: justify;">On the basis of the Institute of Physical Culture and Judo ASU grew more than one generation of Honored Master of Sports, World Champion, European and Olympic Games. Among them: V.Nevzorov – the first Soviet world champion in judo, Olympic champion (1976); A. Emizh – Olympic bronze medalist (1980), European champion in judo; Khasanov – 11-time world champion and 7-time European champion, 4-time winner of the World Cup, the 19-time champion of Russia in Sambo; H.Tletseri – one of the most titled judoka Russia and the world; S.Aliferenko – Olympic champion in shooting. List of high sports achievements the university has expanded in 2010, men’s basketball team “Dinamo-ASU”, has become the champion of Major League. ASU Women’s team handball is a leader in the Super League of the Russian Federation, ASU players repeatedly took to the top places in the championship of the Southern Federal District. older traditions continue today’s students – master of sports of international class in Russia: A. Alifirenko – a three-time champion, bronze medalist of world championships, seven-time winner of the European championships, ten times winner of the championships of Russia among juniors and youth, silver and bronze medalist Russia in shooting; A. Yevtushenko – a member of the Russian national team in cycling, three-time medalist of the championships of Russia and winner of the Cup of Russia among juniors, champion of Russia; A. Borsov – a three-time champion of Russia, European and world champion, three-time winner of the World Cup in kickboxing and more. al.</p>
<p style="text-align: justify;">The university created the necessary conditions for recreational activities and recreational activities: operating sanatorium “Health”, there are two educational and recreational base on the Black Sea coast and the educational and health complex “Mountain Legend”, located in the scenic mountainous area.</p>
<p style="text-align: justify;">Since 1989, the newspaper “Adyghe University” is published in the ASU. Since 2012, the newspaper is the winner of the All-Russian competition of student publications and young journalists “Crystal Arrow”, established by the Ministry of Education and Science of the Russian Federation, Government of Moscow and the Moscow Student Centre, and among the top five Russian student newspapers.</p>
<p style="text-align: justify;">Adygei University occupies a strong position in the scientific and educational community of the Southern Federal District and Russia as a whole and makes every effort to conquer new frontiers, to achieve the highest rating, and always be at the center of scientific progress and the global public interest.</p>
    </div>
</div>


<?php include $path.'/layouts/sidebar.php' ?>
<?php include $path.'/layouts/footer.php' ?>
